// Übersetzung der (englischen) Lichess-Eröffnungsnamen ins Deutsche – Wort- und Phrasenweise.
const PHRASES: [RegExp, string][] = [
  [/King's Pawn Game/g, 'Königsbauernspiel'],
  [/Queen's Pawn Game/g, 'Damenbauernspiel'],
  [/King's Pawn Opening/g, 'Königsbauernspiel'],
  [/Queen's Pawn Opening/g, 'Damenbauernspiel'],
  [/Queen's Gambit Declined/g, 'Abgelehntes Damengambit'],
  [/Queen's Gambit Accepted/g, 'Angenommenes Damengambit'],
  [/Queen's Gambit/g, 'Damengambit'],
  [/King's Gambit Declined/g, 'Abgelehntes Königsgambit'],
  [/King's Gambit Accepted/g, 'Angenommenes Königsgambit'],
  [/King's Gambit/g, 'Königsgambit'],
  [/King's Indian Defense/g, 'Königsindische Verteidigung'],
  [/King's Indian Attack/g, 'Königsindischer Angriff'],
  [/Queen's Indian Defense/g, 'Damenindische Verteidigung'],
  [/Nimzo-Indian Defense/g, 'Nimzoindische Verteidigung'],
  [/Bogo-Indian Defense/g, 'Bogoindische Verteidigung'],
  [/Old Indian Defense/g, 'Altindische Verteidigung'],
  [/Indian Defense/g, 'Indische Verteidigung'],
  [/Sicilian Defense/g, 'Sizilianische Verteidigung'],
  [/French Defense/g, 'Französische Verteidigung'],
  [/Caro-Kann Defense/g, 'Caro-Kann-Verteidigung'],
  [/Scandinavian Defense/g, 'Skandinavische Verteidigung'],
  [/Alekhine Defense/g, 'Aljechin-Verteidigung'],
  [/Pirc Defense/g, 'Pirc-Verteidigung'],
  [/Modern Defense/g, 'Moderne Verteidigung'],
  [/Dutch Defense/g, 'Holländische Verteidigung'],
  [/Philidor Defense/g, 'Philidor-Verteidigung'],
  [/Petrov's Defense/g, 'Russische Verteidigung'],
  [/Russian Game/g, 'Russische Partie'],
  [/Grünfeld Defense/g, 'Grünfeld-Indisch'],
  [/Slav Defense/g, 'Slawische Verteidigung'],
  [/Semi-Slav Defense/g, 'Halbslawische Verteidigung'],
  [/Ruy Lopez/g, 'Spanische Partie'],
  [/Italian Game/g, 'Italienische Partie'],
  [/Scotch Game/g, 'Schottische Partie'],
  [/Vienna Game/g, 'Wiener Partie'],
  [/Four Knights Game/g, 'Vierspringerspiel'],
  [/Three Knights Opening/g, 'Dreispringerspiel'],
  [/Two Knights Defense/g, 'Zweispringerspiel im Nachzuge'],
  [/Bishop's Opening/g, 'Läuferspiel'],
  [/English Opening/g, 'Englische Eröffnung'],
  [/Réti Opening/g, 'Réti-Eröffnung'],
  [/London System/g, 'Londoner System'],
  [/Catalan Opening/g, 'Katalanische Eröffnung'],
  [/Benoni Defense/g, 'Benoni-Verteidigung'],
  [/Benko Gambit/g, 'Wolga-Gambit'],
  [/Budapest Defense/g, 'Budapester Gambit'],
  [/Evans Gambit/g, 'Evansgambit'],
  [/Danish Gambit/g, 'Nordisches Gambit'],
  [/Center Game/g, 'Mittelgambit'],
  [/Ponziani Opening/g, 'Ponziani-Eröffnung'],
  [/Bird Opening/g, 'Bird-Eröffnung'],
  [/Polish Opening/g, 'Polnische Eröffnung'],
  [/Nimzo-Larsen Attack/g, 'Nimzowitsch-Larsen-Angriff'],
  [/Trompowsky Attack/g, 'Trompowsky-Angriff'],
  [/Colle System/g, 'Colle-System'],
  [/Stonewall Attack/g, 'Stonewall-Angriff'],
  [/Giuoco Piano/g, 'Giuoco Piano'],
  [/Berlin Defense/g, 'Berliner Verteidigung'],
  [/Morphy Defense/g, 'Morphy-Verteidigung'],
  [/Closed Variation/g, 'Geschlossene Variante'],
  [/Open Variation/g, 'Offene Variante'],
  [/Exchange Variation/g, 'Abtauschvariante'],
  [/Advance Variation/g, 'Vorstoßvariante'],
  [/Main Line/g, 'Hauptvariante'],
  [/English Attack/g, 'Englischer Angriff'],
  [/Dragon Variation/g, 'Drachenvariante'],
  [/Accelerated Dragon/g, 'Beschleunigter Drache'],
  [/Poisoned Pawn/g, 'Vergifteter Bauer'],
  [/Fried Liver Attack/g, 'Fried-Liver-Angriff'],
  [/Mar del Plata/g, 'Mar del Plata'],
  [/Classical Variation/g, 'Klassische Variante'],
  [/Modern Variation/g, 'Moderne Variante'],
];
const WORDS: [RegExp, string][] = [
  // Eigennamen + Typ: „Najdorf Variation“ → „Najdorf-Variante“
  [/([A-ZÄÖÜ][\wäöüé'-]+) Variation\b/g, '$1-Variante'],
  [/([A-ZÄÖÜ][\wäöüé'-]+) Defense\b/g, '$1-Verteidigung'],
  [/([A-ZÄÖÜ][\wäöüé'-]+) Attack\b/g, '$1-Angriff'],
  [/([A-ZÄÖÜ][\wäöüé'-]+) Gambit\b/g, '$1-Gambit'],
  [/([A-ZÄÖÜ][\wäöüé'-]+) System\b/g, '$1-System'],
  [/\bDefense\b/g, 'Verteidigung'],
  [/\bOpening\b/g, 'Eröffnung'],
  [/\bGame\b/g, 'Partie'],
  [/\bAttack\b/g, 'Angriff'],
  [/\bVariation\b/g, 'Variante'],
  [/\bSystem\b/g, 'System'],
  [/\bDeclined\b/g, 'abgelehnt'],
  [/\bAccepted\b/g, 'angenommen'],
  [/\bClassical\b/g, 'Klassisch'],
  [/\bModern\b/g, 'Modern'],
  [/\bClosed\b/g, 'Geschlossen'],
  [/\bOpen\b/g, 'Offen'],
  [/\bExchange\b/g, 'Abtausch'],
  [/\bAdvance\b/g, 'Vorstoß'],
  [/\bCounterattack\b/g, 'Gegenangriff'],
  [/\bCountergambit\b/g, 'Gegengambit'],
  [/\bLine\b/g, 'Linie'],
  [/\bMain\b/g, 'Haupt'],
  [/\bSicilian\b/g, 'Sizilianisch'],
  [/\bFrench\b/g, 'Französisch'],
  [/\bEnglish\b/g, 'Englisch'],
  [/\bItalian\b/g, 'Italienisch'],
  [/\bSpanish\b/g, 'Spanisch'],
  [/\bDutch\b/g, 'Holländisch'],
  [/\bRussian\b/g, 'Russisch'],
  [/\bScotch\b/g, 'Schottisch'],
  [/\bIndian\b/g, 'Indisch'],
  [/\bKing's\b/g, 'Königs-'],
  [/\bQueen's\b/g, 'Damen-'],
  [/\bKnight\b/g, 'Springer'],
  [/\bKnights\b/g, 'Springer'],
  [/\bBishop\b/g, 'Läufer'],
  [/\bPawn\b/g, 'Bauer'],
  [/\bTrap\b/g, 'Falle'],
  [/\bWing\b/g, 'Flügel'],
  [/\bLeningrad\b/g, 'Leningrader'],
  [/\bOrthodox\b/g, 'Orthodox'],
  [/\bAccelerated\b/g, 'Beschleunigt'],
  [/\bReversed\b/g, 'mit vertauschten Farben'],
  [/\bDeferred\b/g, 'verzögert'],
  [/\bAnti-/g, 'Anti-'],
];

export function openingDe(name: string): string {
  let s = name;
  for (const [r, t] of PHRASES) s = s.replace(r, t);
  for (const [r, t] of WORDS) s = s.replace(r, t);
  return s.replace(/-\s/g, '-').replace(/\s{2,}/g, ' ');
}
