// Fachbegriffe-Heft: knappe Erklärung + Diagramm.
// Diagramm entweder als FEN oder als Zugfolge (SAN) ab `fen` bzw. Grundstellung.

export type GlossaryCat =
  | 'Regeln & Grundbegriffe'
  | 'Taktik'
  | 'Mattbilder'
  | 'Bauernstruktur'
  | 'Strategie'
  | 'Eröffnung'
  | 'Endspiel';

export interface GlossaryEntry {
  id: string;
  term: string;
  cat: GlossaryCat;
  text: string;
  /** Kurze Bildunterschrift zum Diagramm */
  ex?: string;
  fen?: string;
  moves?: string[];
  arrows?: string[];
  hl?: string[];
  flip?: boolean;
  /** Verwandte Begriffe (ids) */
  see?: string[];
  /** Passende Lektion */
  lesson?: string;
}

const W = ' w - - 0 1';
const B = ' b - - 0 1';

export const GLOSSARY: GlossaryEntry[] = [
  // ───────── Regeln & Grundbegriffe ─────────
  { id: 'schach', term: 'Schach', cat: 'Regeln & Grundbegriffe', text: 'Der König wird angegriffen. Der Angegriffene muss sofort reagieren: ziehen, dazwischenstellen oder den Angreifer schlagen.', ex: 'Der Turm e1 gibt Schach.', fen: '4k3/8/8/8/8/8/8/4RK2' + B, arrows: ['e1e8'], see: ['matt', 'doppelschach'], lesson: 'g-schach-matt' },
  { id: 'matt', term: 'Schachmatt', cat: 'Regeln & Grundbegriffe', text: 'Der König steht im Schach und hat keine Rettung mehr. Die Partie ist sofort zu Ende.', ex: 'Grundreihenmatt: Der Turm a8 setzt matt.', fen: 'R5k1/5ppp/8/8/8/8/8/6K1' + B, arrows: ['a8g8'], see: ['schach', 'patt'], lesson: 'g-schach-matt' },
  { id: 'patt', term: 'Patt', cat: 'Regeln & Grundbegriffe', text: 'Die Seite am Zug steht nicht im Schach, hat aber keinen legalen Zug. Ergebnis: Remis.', ex: 'Schwarz ist am Zug – kein Zug möglich.', fen: 'k7/2Q5/1K6/8/8/8/8/8' + B, hl: ['a7', 'b7', 'b8'], see: ['matt', 'remis'], lesson: 'g-schach-matt' },
  { id: 'remis', term: 'Remis', cat: 'Regeln & Grundbegriffe', text: 'Unentschieden. Entsteht durch Patt, Einigung, dreifache Wiederholung, 50-Züge-Regel oder zu wenig Material.', ex: 'König + Läufer gegen König: Matt ist unmöglich.', fen: '8/8/4k3/8/8/2BK4/8/8' + W, see: ['patt', 'dauerschach', 'fuenfzig'] },
  { id: 'dauerschach', term: 'Dauerschach', cat: 'Regeln & Grundbegriffe', text: 'Eine Seite kann endlos Schach geben, ohne dass der Gegner entkommt. Führt zum Remis durch Wiederholung.', ex: 'Die schwarze Dame pendelt zwischen e1 und h4.', fen: '6k1/5ppp/8/8/8/8/6PP/4q2K' + W, arrows: ['e1h4', '?h4e1'], see: ['remis'] },
  { id: 'fuenfzig', term: '50-Züge-Regel', cat: 'Regeln & Grundbegriffe', text: 'Nach 50 Zügen jeder Seite ohne Bauernzug und ohne Schlagen kann Remis beansprucht werden.', ex: 'Wichtig bei langen Endspielen wie Läufer + Springer.', fen: '8/8/8/4k3/8/8/8/1N2KB2' + W, see: ['remis'] },
  { id: 'rochade', term: 'Rochade', cat: 'Regeln & Grundbegriffe', text: 'Doppelzug von König und Turm: Der König zieht zwei Felder zum Turm, der Turm springt über ihn. Bringt den König in Sicherheit.', ex: 'Kurze Rochade: Ke1–g1, Th1–f1.', fen: '4k3/8/8/8/8/8/5PPP/4K2R' + W, arrows: ['e1g1', 'h1f1'], see: ['lange-rochade'], lesson: 'g-sonderzuege' },
  { id: 'lange-rochade', term: 'Lange Rochade', cat: 'Regeln & Grundbegriffe', text: 'Rochade zum Damenflügel (O-O-O). Der Turm landet sofort auf der d-Linie – oft mit entgegengesetzten Rochaden und gegenseitigen Angriffen.', ex: 'Ke1–c1, Ta1–d1.', fen: '4k3/8/8/8/8/8/PPP5/R3K3' + W, arrows: ['e1c1', 'a1d1'], see: ['rochade'] },
  { id: 'en-passant', term: 'En passant', cat: 'Regeln & Grundbegriffe', text: '„Im Vorbeigehen“: Zieht ein Bauer mit Doppelschritt neben einen gegnerischen Bauern, darf dieser ihn im direkt nächsten Zug schlagen, als wäre er nur ein Feld gezogen.', ex: 'Schwarz spielte d7–d5. Jetzt exd6 e.p.', fen: 'rnbqkbnr/ppp1pppp/8/3pP3/8/8/PPPP1PPP/RNBQKBNR w KQkq d6 0 3', arrows: ['e5d6', 'd5'], lesson: 'g-sonderzuege' },
  { id: 'umwandlung', term: 'Umwandlung', cat: 'Regeln & Grundbegriffe', text: 'Erreicht ein Bauer die letzte Reihe, wird er in Dame, Turm, Läufer oder Springer umgewandelt – fast immer in eine Dame.', ex: 'e7–e8 = neue Dame.', fen: '8/4P1k1/8/8/8/8/8/4K3' + W, arrows: ['e7e8'], see: ['unterverwandlung', 'freibauer'] },
  { id: 'unterverwandlung', term: 'Unterverwandlung', cat: 'Regeln & Grundbegriffe', text: 'Umwandlung in etwas anderes als die Dame – etwa in einen Springer für eine Gabel mit Schach oder in einen Turm, um Patt zu vermeiden.', ex: 'c8=S+ gabelt König und Dame.', fen: '8/2P1k3/1q6/8/8/8/1P6/K7' + W, arrows: ['c7c8', 'e7', 'b6'], see: ['umwandlung', 'gabel'], lesson: 'g-sonderzuege' },
  { id: 'notation', term: 'Algebraische Notation', cat: 'Regeln & Grundbegriffe', text: 'Jedes Feld hat einen Namen aus Linie (a–h) und Reihe (1–8). Züge schreibt man mit Figurenbuchstaben: K, D, T, L, S (Bauer ohne Buchstabe), z. B. Sf3 oder exd5.', ex: 'Markiert: a1, e4 und h8.', fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', hl: ['a1', 'e4', 'h8'] },
  { id: 'figurenwert', term: 'Figurenwert', cat: 'Regeln & Grundbegriffe', text: 'Faustregel: Bauer 1, Springer 3, Läufer 3, Turm 5, Dame 9. Hilft beim Bewerten von Abtauschen.', ex: 'Die volle weiße Armee.', fen: '4k3/8/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1', see: ['qualitaet', 'tauschbilanz'], lesson: 'g-figuren' },
  { id: 'leichtfigur', term: 'Leichtfigur', cat: 'Regeln & Grundbegriffe', text: 'Springer und Läufer (je etwa 3 Bauern wert). Sie sollten in der Eröffnung zuerst entwickelt werden.', ex: 'Die vier weißen Leichtfiguren.', fen: '4k3/8/8/8/8/8/8/1NB1KBN1 w - - 0 1', hl: ['b1', 'c1', 'f1', 'g1'], see: ['schwerfigur', 'entwicklung'] },
  { id: 'schwerfigur', term: 'Schwerfigur', cat: 'Regeln & Grundbegriffe', text: 'Turm und Dame. Sie brauchen offene Linien und entfalten ihre Kraft meist erst im Mittel- und Endspiel.', ex: 'Türme und Dame.', fen: '4k3/8/8/8/8/8/8/R2QK2R w KQ - 0 1', hl: ['a1', 'd1', 'h1'], see: ['leichtfigur', 'offene-linie'] },
  { id: 'qualitaet', term: 'Qualität', cat: 'Regeln & Grundbegriffe', text: 'Der Wertunterschied zwischen Turm und Leichtfigur. Wer einen Turm für einen Springer oder Läufer bekommt, „gewinnt die Qualität“.', ex: 'Txd4 wäre ein Qualitätsopfer.', fen: '4k3/8/8/8/3n4/8/8/3RK3' + W, arrows: ['!d1d4'], see: ['qualitaetsopfer', 'figurenwert'] },
  { id: 'linie', term: 'Linie', cat: 'Regeln & Grundbegriffe', text: 'Eine senkrechte Spalte des Bretts (a bis h).', ex: 'Die e-Linie.', fen: '7k/8/8/8/8/8/8/K7' + W, arrows: ['e1e8'], see: ['reihe', 'diagonale'] },
  { id: 'reihe', term: 'Reihe', cat: 'Regeln & Grundbegriffe', text: 'Eine waagerechte Zeile des Bretts (1 bis 8).', ex: 'Die 4. Reihe.', fen: '7k/8/8/8/8/8/8/K7' + W, arrows: ['a4h4'], see: ['linie', 'siebte-reihe'] },
  { id: 'diagonale', term: 'Diagonale', cat: 'Regeln & Grundbegriffe', text: 'Eine schräge Felderkette gleicher Farbe. Läufer und Dame wirken auf Diagonalen.', ex: 'Die lange Diagonale a1–h8.', fen: '6k1/8/8/8/8/8/8/K7' + W, arrows: ['b2h8'], see: ['fianchetto'] },
  { id: 'fluegel', term: 'Damen- und Königsflügel', cat: 'Regeln & Grundbegriffe', text: 'Die a- bis d-Linie heißt Damenflügel, die e- bis h-Linie Königsflügel – benannt nach der Grundstellung.', ex: 'Links der Damenflügel, rechts der Königsflügel.', fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', arrows: ['d1', 'e1'], see: ['bauernmajoritaet'] },
  { id: 'tempo', term: 'Tempo', cat: 'Regeln & Grundbegriffe', text: 'Ein Zug als Zeiteinheit. Wer mit Drohung entwickelt, „gewinnt ein Tempo“; unnütze Züge „verlieren Tempi“.', ex: 'Sc3 greift die Dame an und entwickelt – Tempogewinn.', moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3'], arrows: ['c3d5'], see: ['entwicklung', 'initiative'] },

  // ───────── Taktik ─────────
  { id: 'gabel', term: 'Gabel', cat: 'Taktik', text: 'Eine Figur greift zwei oder mehr gegnerische Figuren gleichzeitig an.', ex: 'Springergabel auf c7: König und Turm.', fen: 'r3k3/2N5/8/8/8/8/7P/4K3' + B, arrows: ['c7e8', 'c7a8'], see: ['doppelangriff'], lesson: 't-gabel' },
  { id: 'doppelangriff', term: 'Doppelangriff', cat: 'Taktik', text: 'Zwei Drohungen mit einem Zug – z. B. Schach und Angriff auf eine ungedeckte Figur. Oberbegriff der Gabel.', ex: 'Dd5+ trifft König und Turm a2.', fen: '6k1/6pp/8/3Q4/8/8/r4PPP/6K1' + B, arrows: ['d5g8', 'd5a2'], see: ['gabel', 'haengende-figur'] },
  { id: 'fesselung', term: 'Fesselung', cat: 'Taktik', text: 'Eine Figur kann nicht (oder nur mit Verlust) ziehen, weil dahinter eine wertvollere Figur steht. Steht dahinter der König, ist sie absolut.', ex: 'Der Springer c6 ist an den König gefesselt.', fen: '4k3/8/2n5/1B6/8/8/8/4K3' + W, arrows: ['b5e8'], see: ['relative-fesselung', 'spiess'], lesson: 't-fesselung' },
  { id: 'relative-fesselung', term: 'Relative Fesselung', cat: 'Taktik', text: 'Die gefesselte Figur dürfte ziehen, aber dann ginge eine wertvollere Figur dahinter verloren.', ex: 'Td1 fesselt den Springer an die Dame d8.', fen: '3q2k1/8/8/8/3n4/8/8/K2R4' + W, arrows: ['d1d8'], see: ['fesselung'] },
  { id: 'spiess', term: 'Spieß', cat: 'Taktik', text: 'Umgekehrte Fesselung: Die wertvolle Figur vorne wird angegriffen und muss weichen, die Figur dahinter geht verloren.', ex: 'Ta6+ – danach fällt die Dame h6.', fen: '8/8/2k4q/8/8/8/8/R5K1' + W, arrows: ['a1a6', '?a6h6'], see: ['fesselung'], lesson: 't-spiess' },
  { id: 'abzug', term: 'Abzugsangriff', cat: 'Taktik', text: 'Eine Figur zieht weg und gibt die Linie einer anderen Figur frei – zwei Angriffe in einem Zug.', ex: 'Sf6+ öffnet die Diagonale g2–a8.', fen: 'q3k3/7p/8/8/4N3/8/5PBP/6K1' + W, arrows: ['e4f6', 'g2a8'], see: ['doppelschach'], lesson: 't-abzug' },
  { id: 'doppelschach', term: 'Doppelschach', cat: 'Taktik', text: 'Zwei Figuren geben gleichzeitig Schach. Nur ein Königszug hilft.', ex: 'Springer h6 und Dame c4 geben beide Schach.', fen: '4r1k1/6pp/7N/8/2Q5/8/8/6K1' + B, arrows: ['h6g8', 'c4g8'], see: ['abzug'] },
  { id: 'ablenkung', term: 'Ablenkung', cat: 'Taktik', text: 'Ein Verteidiger wird durch Opfer oder Schach von seiner Aufgabe weggelockt.', ex: 'Te8+! lenkt den Turm b8 ab – d7–d8 folgt.', fen: '1r4k1/3P1ppp/8/8/8/8/5PPP/4R1K1' + W, arrows: ['e1e8', '?b8e8', 'd7d8'], see: ['ueberlastung'], lesson: 't-ablenkung' },
  { id: 'hinlenkung', term: 'Hinlenkung', cat: 'Taktik', text: 'Eine gegnerische Figur wird auf ein bestimmtes (schlechtes) Feld gezwungen – oft durch ein Opfer.', ex: 'Dg8+!! zwingt den Turm nach g8.', fen: '4r2k/6pp/7N/8/2Q5/8/8/6K1' + W, arrows: ['c4g8'], see: ['ersticktes-matt'], lesson: 't-philidor' },
  { id: 'ueberlastung', term: 'Überlastung', cat: 'Taktik', text: 'Eine Figur muss zwei Aufgaben gleichzeitig erfüllen – und schafft keine richtig.', ex: 'Te8 deckt e5 und die Grundreihe: Txe5! Txe5 Td8+.', fen: '4r1k1/5ppp/8/4n3/8/8/5PPP/3RR1K1' + W, arrows: ['e1e5', 'd1d8'], see: ['ablenkung'] },
  { id: 'verteidiger-beseitigen', term: 'Verteidiger beseitigen', cat: 'Taktik', text: 'Schlage die Figur, die ein wichtiges Feld deckt – danach bricht die Verteidigung zusammen.', ex: 'Lxf6! und Dxh7 matt droht.', fen: 'r4rk1/ppp2ppp/5n2/6BQ/8/3B4/PPP2PPP/R5K1' + W, arrows: ['g5f6', 'h5h7'], see: ['ablenkung'], lesson: 't-ablenkung' },
  { id: 'zwischenzug', term: 'Zwischenzug', cat: 'Taktik', text: 'Statt sofort zurückzuschlagen, wird zuerst ein stärkerer Zug (meist Schach) eingeschoben.', ex: 'Erst Dxd8+, dann bxc3.', fen: 'r2q2k1/5ppp/8/8/8/2b5/PP3PPP/3Q2K1' + W, arrows: ['d1d8', '?b2c3'], see: ['kandidatenzug'] },
  { id: 'roentgen', term: 'Röntgenangriff', cat: 'Taktik', text: 'Eine Figur wirkt durch eine andere hindurch – etwa ein Turm hinter dem anderen auf derselben Linie.', ex: 'Td1 wirkt durch Td2 auf d8.', fen: '3r2k1/5ppp/8/8/8/8/3R1PPP/3R2K1' + W, arrows: ['d1d8'], see: ['batterie'] },
  { id: 'batterie', term: 'Batterie', cat: 'Taktik', text: 'Zwei weitreichende Figuren hintereinander auf einer Linie oder Diagonale, z. B. Dame hinter Läufer gegen h7.', ex: 'Dc2 + Ld3 zielen auf h7.', fen: '6k1/5ppp/8/8/8/3B4/2Q2PPP/6K1' + W, arrows: ['c2h7'], see: ['roentgen', 'koenigsangriff'] },
  { id: 'haengende-figur', term: 'Hängende Figur', cat: 'Taktik', text: 'Eine ungedeckte (oder zu schwach gedeckte) Figur. Die häufigste Ursache für Materialverlust.', ex: 'Die Dame d5 ist ungedeckt.', fen: '4k3/8/8/3q4/8/8/8/3RK3' + W, arrows: ['d1d5'], see: ['tauschbilanz'], lesson: 'g-figuren' },
  { id: 'tauschbilanz', term: 'Tauschbilanz', cat: 'Taktik', text: 'Zähle Angreifer und Verteidiger eines Feldes und schlage mit der billigsten Figur zuerst.', ex: 'd5: drei Angreifer gegen zwei Verteidiger.', fen: 'r2qk2r/ppp2ppp/4p3/3n4/8/1BN5/PPP2PPP/3R1RK1 w kq - 0 1', arrows: ['c3d5', 'b3d5', 'd1d5'], see: ['haengende-figur'], lesson: 'g-tauschbilanz' },
  { id: 'opfer', term: 'Opfer', cat: 'Taktik', text: 'Freiwillige Materialabgabe für Angriff, Matt oder späteren Gewinn.', ex: 'Das Griechische Geschenk Lxh7+.', fen: 'r2q1rk1/1b3ppp/p3p3/1pbnP3/8/3B1N2/PP3PPP/R1BQ1RK1' + W, arrows: ['d3h7'], see: ['griechisches-geschenk', 'gambit'] },
  { id: 'griechisches-geschenk', term: 'Griechisches Geschenk', cat: 'Taktik', text: 'Das Läuferopfer Lxh7+ gegen die kurze Rochade, gefolgt von Sg5+ und Dh5.', ex: 'Nach Lxh7+ Kxh7 Sg5+ ist der König entblößt.', fen: 'r2q1rk1/1b3ppp/p3p3/1pbnP3/8/3B1N2/PP3PPP/R1BQ1RK1' + W, moves: ['Bxh7+', 'Kxh7', 'Ng5+'], arrows: ['d1h5'], see: ['opfer'], lesson: 't-griechisches-geschenk' },
  { id: 'kandidatenzug', term: 'Kandidatenzug', cat: 'Taktik', text: 'Ein Zug, den man ernsthaft prüft. Profis suchen zuerst 2–4 Kandidaten: Schachs, Schläge, Drohungen – dann rechnen sie.', ex: 'Vier Kandidaten im ersten Zug.', fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', arrows: ['e2e4', 'd2d4', '?g1f3', '?c2c4'] },
  { id: 'stiller-zug', term: 'Stiller Zug', cat: 'Taktik', text: 'Ein Zug ohne Schach und ohne Schlagen, der trotzdem eine entscheidende Drohung aufstellt.', ex: 'Dh5! – still, aber Dh7 matt droht.', fen: 'r2q1r2/1b3ppk/p3p3/1pbnP1N1/8/8/PP3PPP/R1BQ1RK1 b - - 0 1', moves: ['Kg8', 'Qh5'], arrows: ['h5h7'], see: ['griechisches-geschenk'] },
  { id: 'mattdrohung', term: 'Mattdrohung', cat: 'Taktik', text: 'Ein Zug, der im nächsten Zug Matt droht. Sie zwingt den Gegner zur Verteidigung und schafft Zeit für andere Pläne.', ex: 'Weiß droht Dxf7 matt.', moves: ['e4', 'e5', 'Bc4', 'Nc6', 'Qh5'], arrows: ['h5f7', 'c4f7'], see: ['schaefermatt'] },
  { id: 'kombination', term: 'Kombination', cat: 'Taktik', text: 'Eine erzwungene Zugfolge, meist mit Opfer, die zu einem klaren Vorteil führt.', ex: 'Philidors Vermächtnis: Sf7+, Sh6++, Dg8+!!, Sf7#.', fen: '4r2k/6pp/8/6N1/2Q5/8/8/6K1' + W, arrows: ['g5f7', 'c4g8'], see: ['ersticktes-matt'], lesson: 't-philidor' },

  // ───────── Mattbilder ─────────
  { id: 'grundreihenmatt', term: 'Grundreihenmatt', cat: 'Mattbilder', text: 'Turm oder Dame setzt auf der Grundreihe matt, weil die eigenen Bauern dem König die Flucht versperren.', ex: 'Ta8#', fen: 'R5k1/5ppp/8/8/8/8/8/6K1' + B, hl: ['f7', 'g7', 'h7'], see: ['luftloch'], lesson: 'g-schach-matt' },
  { id: 'ersticktes-matt', term: 'Ersticktes Matt', cat: 'Mattbilder', text: 'Der Springer setzt matt, weil der König von eigenen Figuren eingemauert ist.', ex: 'Sf7#', fen: '6rk/5Npp/8/8/8/8/8/6K1' + B, arrows: ['f7h8'], see: ['hinlenkung'], lesson: 'g-mattbilder' },
  { id: 'arabisches-matt', term: 'Arabisches Matt', cat: 'Mattbilder', text: 'Turm und Springer in der Ecke: Der Springer deckt den Turm und das Fluchtfeld.', ex: 'Th7#', fen: '7k/7R/5N2/8/8/8/8/7K' + B, arrows: ['f6h7'], lesson: 'g-mattbilder' },
  { id: 'anastasia-matt', term: 'Anastasia-Matt', cat: 'Mattbilder', text: 'Springer e7 und Turm auf der h-Linie setzen den König am Rand matt, der eigene g-Bauer sperrt ihn ein.', ex: 'Th5#', fen: '8/4N1pk/8/7R/8/8/8/6K1' + B, arrows: ['h5h7', 'e7g8'] },
  { id: 'bodens-matt', term: 'Bodens Matt', cat: 'Mattbilder', text: 'Zwei Läufer auf sich kreuzenden Diagonalen setzen den lang rochierten König matt.', ex: 'La6#', fen: '2kr4/3n4/B7/8/5B2/8/8/6K1' + B, arrows: ['a6c8', 'f4b8'] },
  { id: 'epaulettenmatt', term: 'Epaulettenmatt', cat: 'Mattbilder', text: 'Der König wird von zwei eigenen Figuren links und rechts eingeklemmt – wie Schulterklappen.', ex: 'De6#', fen: '3rkr2/8/4Q3/8/8/8/8/6K1' + B, arrows: ['e6e8'] },
  { id: 'kuss-des-todes', term: 'Kuss des Todes', cat: 'Mattbilder', text: 'Die Dame setzt direkt neben dem König matt, gedeckt von einer eigenen Figur.', ex: 'Dg7# – gedeckt von f6.', fen: '6k1/5pQp/5Pp1/8/8/8/8/6K1' + B, arrows: ['f6g7'], lesson: 'g-mattbilder' },
  { id: 'treppenmatt', term: 'Treppenmatt', cat: 'Mattbilder', text: 'Zwei Schwerfiguren treiben den König im Wechsel Reihe für Reihe an den Rand.', ex: 'Tb7 hält die 7. Reihe, Ta8#.', fen: 'R5k1/1R6/8/8/8/8/8/6K1' + B, arrows: ['b7h7'], lesson: 'g-mattbilder' },
  { id: 'schaefermatt', term: 'Schäfermatt', cat: 'Mattbilder', text: 'Frühes Matt auf f7 durch Dame und Läufer c4. Abwehr: f7 decken und mit Tempo entwickeln.', ex: 'Dxf7#', moves: ['e4', 'e5', 'Bc4', 'Nc6', 'Qh5', 'Nf6', 'Qxf7#'], arrows: ['c4f7'], lesson: 'g-schaefermatt' },
  { id: 'narrenmatt', term: 'Narrenmatt', cat: 'Mattbilder', text: 'Das schnellste Matt überhaupt (2 Züge), nach zwei schwachen Bauernzügen von Weiß.', ex: '1.f3 e5 2.g4 Dh4#', moves: ['f3', 'e5', 'g4', 'Qh4#'], arrows: ['h4e1'] },
  { id: 'legall-matt', term: 'Legall-Matt', cat: 'Mattbilder', text: 'Scheinbares Damenopfer: Nach Lxd1 setzen die Leichtfiguren matt. Benannt nach Legall (18. Jh.).', ex: '8.Sd5#', moves: ['e4', 'e5', 'Nf3', 'd6', 'Bc4', 'Nc6', 'Nc3', 'Bg4', 'h3', 'Bh5', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'], arrows: ['d5e7'] },

  // ───────── Bauernstruktur ─────────
  { id: 'isolani', term: 'Isolierter Bauer (Isolani)', cat: 'Bauernstruktur', text: 'Ein Bauer ohne eigene Nachbarbauern auf den Nebenlinien. Er braucht Figuren als Schutz; das Feld vor ihm ist ein idealer Blockadepunkt.', ex: 'Der weiße Isolani d4.', moves: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'c4', 'Nf6', 'Nc3', 'e6', 'Nf3', 'Be7', 'cxd5', 'Nxd5', 'Bd3', 'Nc6', 'O-O', 'O-O', 'Re1'], hl: ['d4'], arrows: ['d5'], see: ['blockade'], lesson: 's-isolani' },
  { id: 'doppelbauer', term: 'Doppelbauer', cat: 'Bauernstruktur', text: 'Zwei eigene Bauern auf derselben Linie. Meist eine Schwäche, weil sie sich nicht gegenseitig decken können.', ex: 'Doppelbauer auf c2 und c3.', fen: '4k3/pp3ppp/8/8/8/2P5/P1P2PPP/4K3' + W, hl: ['c2', 'c3'] },
  { id: 'rueckstaendiger-bauer', term: 'Rückständiger Bauer', cat: 'Bauernstruktur', text: 'Ein Bauer, dessen Nachbarn schon vorgerückt sind und der selbst nicht sicher vorziehen kann.', ex: 'd6 ist rückständig, d5 gehört Weiß.', fen: '4k3/pp3ppp/3p4/2p1p3/4P3/2N5/PPP2PPP/4K3' + W, hl: ['d6'], arrows: ['c3d5'], see: ['loch'] },
  { id: 'freibauer', term: 'Freibauer', cat: 'Bauernstruktur', text: 'Ein Bauer, den kein gegnerischer Bauer mehr aufhalten kann – weder auf seiner Linie noch auf den Nachbarlinien.', ex: 'b5 ist frei.', fen: '4k3/5ppp/8/1P6/8/8/5PPP/4K3' + W, arrows: ['b5b8'], see: ['entfernter-freibauer', 'gedeckter-freibauer'] },
  { id: 'verbundene-freibauern', term: 'Verbundene Freibauern', cat: 'Bauernstruktur', text: 'Zwei Freibauern auf benachbarten Linien. Sie schützen sich gegenseitig und sind oft stärker als eine Figur.', ex: 'c5 und d5.', fen: '4k3/8/8/2PP4/8/8/8/4K3' + W, hl: ['c5', 'd5'], see: ['freibauer'] },
  { id: 'entfernter-freibauer', term: 'Entfernter Freibauer', cat: 'Bauernstruktur', text: 'Ein Freibauer weit weg vom übrigen Geschehen. Er lenkt den gegnerischen König ab.', ex: 'Der a-Bauer zieht den König weg.', fen: '8/5pp1/4k3/8/P3K3/8/5PP1/8' + W, arrows: ['a4a8'], lesson: 's-freibauer' },
  { id: 'gedeckter-freibauer', term: 'Gedeckter Freibauer', cat: 'Bauernstruktur', text: 'Ein Freibauer, der von einem eigenen Bauern gedeckt wird. Der gegnerische König kann ihn nicht schlagen.', ex: 'd6, gedeckt von c5.', fen: '4k3/8/3P4/2P5/8/8/8/4K3' + W, arrows: ['c5d6'] },
  { id: 'bauernkette', term: 'Bauernkette', cat: 'Bauernstruktur', text: 'Diagonal verbundene Bauern. Angriffspunkt ist die Basis – der hinterste Bauer.', ex: 'Kette d4–e5, Basis d4.', moves: ['e4', 'e6', 'd4', 'd5', 'e5'], hl: ['d4', 'e5'], arrows: ['c7c5'], lesson: 's-bauernkette' },
  { id: 'bauernmajoritaet', term: 'Bauernmajorität', cat: 'Bauernstruktur', text: 'Mehr Bauern an einem Flügel als der Gegner. Aus ihr lässt sich ein Freibauer bilden.', ex: 'Weiß: 3 gegen 2 am Damenflügel.', fen: '4k3/pp3ppp/8/8/8/8/PPP3PP/4K3' + W, hl: ['a2', 'b2', 'c2'], see: ['minoritaetsangriff'] },
  { id: 'minoritaetsangriff', term: 'Minoritätsangriff', cat: 'Bauernstruktur', text: 'Die Minderheit (z. B. 2 Bauern) greift eine Mehrheit (3 Bauern) an, um Schwächen zu erzeugen.', ex: 'b4–b5 in der Karlsbader Struktur.', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'cxd5', 'exd5', 'Bg5', 'c6', 'e3', 'Be7', 'Bd3', 'Nbd7', 'Nge2', 'O-O', 'O-O', 'Re8', 'Rb1', 'Nf8'], arrows: ['b2b4', 'b4b5'], lesson: 's-minoritaetsangriff' },
  { id: 'haengende-bauern', term: 'Hängende Bauern', cat: 'Bauernstruktur', text: 'Zwei nebeneinanderstehende Bauern (meist c und d) ohne Nachbarbauern. Stark im Zentrum, aber leicht angreifbar.', ex: 'Schwarz: c5 und d5.', fen: '4k3/p4ppp/8/2pp4/8/4P3/PP3PPP/4K3' + W, hl: ['c5', 'd5'], see: ['isolani'] },
  { id: 'bauernhebel', term: 'Bauernhebel', cat: 'Bauernstruktur', text: 'Ein Bauernzug, der einen gegnerischen Bauern angreift und die Struktur aufbricht.', ex: '…c5 greift d4 an.', moves: ['e4', 'e6', 'd4', 'd5', 'e5'], arrows: ['c7c5', '?f7f6'], see: ['bauernkette'] },
  { id: 'bauerninsel', term: 'Bauerninsel', cat: 'Bauernstruktur', text: 'Eine Gruppe verbundener Bauern. Je weniger Inseln, desto gesünder die Struktur.', ex: 'Schwarz hat vier Inseln, Weiß zwei.', fen: '4k3/p2p1p1p/8/8/8/8/PPP2PPP/4K3' + W, hl: ['a7', 'd7', 'f7', 'h7'] },
  { id: 'durchbruch', term: 'Bauerndurchbruch', cat: 'Bauernstruktur', text: 'Bauern opfern sich, um einem Kameraden den Weg zur Umwandlung zu bahnen.', ex: 'b6! und ein Bauer kommt durch.', fen: '8/ppp3k1/8/PPP5/8/8/8/6K1' + W, arrows: ['b5b6'] },

  // ───────── Strategie ─────────
  { id: 'zentrum', term: 'Zentrum', cat: 'Strategie', text: 'Die Felder d4, e4, d5 und e5. Wer sie kontrolliert, hat mehr Raum und beweglichere Figuren.', fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', arrows: ['d4', 'e4', 'd5', 'e5'], lesson: 'g-prinzipien' },
  { id: 'entwicklung', term: 'Entwicklung', cat: 'Strategie', text: 'Figuren von der Grundreihe ins Spiel bringen. In der Eröffnung das wichtigste Ziel neben Zentrum und Königssicherheit.', ex: 'Beide Seiten haben drei Figuren entwickelt.', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'], lesson: 'g-prinzipien' },
  { id: 'initiative', term: 'Initiative', cat: 'Strategie', text: 'Die Fähigkeit, Drohungen aufzustellen, auf die der Gegner reagieren muss. Wer die Initiative hat, bestimmt das Geschehen.', ex: 'Weiß droht ständig etwas.', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5'], arrows: ['g5f7', 'c4f7'], see: ['tempo'] },
  { id: 'raumvorteil', term: 'Raumvorteil', cat: 'Strategie', text: 'Mehr kontrollierte Felder – meist durch weit vorgerückte Bauern. Die eigenen Figuren haben mehr Platz, die gegnerischen weniger.', ex: 'Weiß hat mit d5 viel Raum.', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6', 'd5', 'Ne7'], hl: ['c4', 'd5', 'e4'] },
  { id: 'offene-linie', term: 'Offene Linie', cat: 'Strategie', text: 'Eine Linie ohne Bauern. Türme gehören auf offene Linien.', ex: 'Die c-Linie ist offen.', fen: 'r4rk1/pp3ppp/4p3/8/3P4/4P3/PP3PPP/R4RK1' + W, arrows: ['c1c8'], lesson: 's-offene-linie' },
  { id: 'halboffene-linie', term: 'Halboffene Linie', cat: 'Strategie', text: 'Eine Linie ohne eigenen, aber mit gegnerischem Bauern. Typisch: die c-Linie für Schwarz im Sizilianer.', ex: 'Schwarz spielt auf der c-Linie.', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4'], arrows: ['c8c2'], flip: true },
  { id: 'siebte-reihe', term: 'Siebte Reihe', cat: 'Strategie', text: 'Ein Turm auf der 7. Reihe greift Bauern an und sperrt den König ein – „Schweine auf der 7.“ bei zwei Türmen.', ex: 'Tb7 greift f7 und a7 an.', fen: '6k1/pR3ppp/8/8/8/8/5PPP/6K1' + W, arrows: ['b7f7', 'b7a7'], see: ['offene-linie'] },
  { id: 'vorposten', term: 'Vorposten', cat: 'Strategie', text: 'Ein Feld, das kein gegnerischer Bauer mehr angreifen kann – ideal für einen Springer.', ex: 'Springer d5 auf dem Vorposten.', fen: '4k3/pp3ppp/3p4/3Np3/4P3/8/PPP2PPP/4K3' + W, hl: ['d5'], see: ['loch'], lesson: 's-vorposten' },
  { id: 'loch', term: 'Loch / Schwaches Feld', cat: 'Strategie', text: 'Ein Feld, das von eigenen Bauern nicht mehr gedeckt werden kann. Der Gegner kann sich dort festsetzen.', ex: 'd5 im Najdorf-Sizilianer.', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be2', 'e5'], arrows: ['d5'], see: ['vorposten'] },
  { id: 'guter-laeufer', term: 'Guter / Schlechter Läufer', cat: 'Strategie', text: 'Ein Läufer ist „schlecht“, wenn die eigenen Bauern auf seiner Feldfarbe stehen und ihn blockieren.', ex: 'Der Läufer c8 ist eingesperrt.', moves: ['e4', 'e6', 'd4', 'd5', 'e5'], arrows: ['!c8h3', 'c8'], lesson: 's-bauernkette' },
  { id: 'laeuferpaar', term: 'Läuferpaar', cat: 'Strategie', text: 'Beide Läufer gegen Springer und Läufer oder zwei Springer. In offenen Stellungen ein Vorteil von etwa einem halben Bauern.', ex: 'Weiß hat beide Läufer.', fen: '4k3/pp1n1ppp/4b3/8/8/8/PP3PPP/2B1KB2' + W, hl: ['c1', 'f1'] },
  { id: 'ungleiche-laeufer', term: 'Ungleichfarbige Läufer', cat: 'Strategie', text: 'Jede Seite hat einen Läufer, aber auf verschiedenen Feldfarben. Im Endspiel sehr remislastig, im Mittelspiel stark für den Angreifer.', ex: 'Weiß hellfeldrig, Schwarz dunkelfeldrig.', fen: '4k3/5ppp/8/2b5/8/3B4/5PPP/6K1' + W, hl: ['c5', 'd3'] },
  { id: 'fianchetto', term: 'Fianchetto', cat: 'Strategie', text: 'Der Läufer wird über g2/g7 oder b2/b7 auf die lange Diagonale entwickelt.', ex: 'Lg7 zielt auf die Mitte.', fen: '5rk1/5pbp/6p1/8/8/8/8/6K1' + W, arrows: ['g7a1'], see: ['diagonale'] },
  { id: 'prophylaxe', term: 'Prophylaxe', cat: 'Strategie', text: 'Vorbeugung: Einen Plan des Gegners verhindern, bevor er ihn ausführen kann.', ex: 'h3 verhindert …Lg4.', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O', 'h3'], arrows: ['!c8g4'] },
  { id: 'blockade', term: 'Blockade', cat: 'Strategie', text: 'Eine Figur stellt sich vor einen gegnerischen Bauern und stoppt ihn. Am besten eignet sich der Springer.', ex: 'Springer d5 blockiert den Isolani.', fen: '4k3/pp3ppp/8/3n4/3P4/8/PP3PPP/4K3' + W, hl: ['d5'], see: ['isolani'] },
  { id: 'qualitaetsopfer', term: 'Qualitätsopfer', cat: 'Strategie', text: 'Turm gegen Leichtfigur geben, um Struktur, Initiative oder Felder zu gewinnen – eine Spezialität von Petrosjan.', ex: 'Txd4 zerstört das Zentrum.', fen: '4k3/8/8/8/3n4/8/8/3RK3' + W, arrows: ['d1d4'], see: ['qualitaet'] },
  { id: 'koenigsangriff', term: 'Königsangriff', cat: 'Strategie', text: 'Konzentrierter Angriff auf den gegnerischen König. Faustregel: mehr Angreifer als Verteidiger in der Nähe des Königs.', ex: 'Dame, Läufer und Springer gegen h7.', fen: 'r2q1rk1/1b3ppp/p3p3/1pbnP3/8/3B1N2/PP3PPP/R1BQ1RK1' + W, arrows: ['d3h7', 'f3g5', 'd1h5'], see: ['griechisches-geschenk'] },
  { id: 'entgegengesetzte-rochaden', term: 'Entgegengesetzte Rochaden', cat: 'Strategie', text: 'Eine Seite rochiert kurz, die andere lang. Beide stürmen mit Bauern gegen den König – wer schneller ist, gewinnt.', ex: 'Englischer Angriff im Najdorf.', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e5', 'Nb3', 'Be6', 'f3', 'Be7', 'Qd2', 'O-O', 'O-O-O'], arrows: ['g2g4', 'b7b5'] },
  { id: 'luftloch', term: 'Luftloch', cat: 'Strategie', text: 'Ein Bauernzug (meist h3/h6), der dem rochierten König ein Fluchtfeld gibt und so Grundreihenmatts verhindert.', ex: '…h6 schafft Luft auf h7.', fen: '6k1/5pp1/7p/8/8/8/5PPP/6K1' + W, arrows: ['h7'], see: ['grundreihenmatt'] },
  { id: 'zugzwang', term: 'Zugzwang', cat: 'Strategie', text: 'Jeder mögliche Zug verschlechtert die eigene Stellung – man müsste eigentlich passen.', ex: 'Schwarz am Zug muss ausweichen.', fen: '8/8/4k3/8/4K3/4P3/8/8' + B, arrows: ['e4', 'e6'], see: ['opposition'] },

  // ───────── Eröffnung ─────────
  { id: 'offene-spiele', term: 'Offene Spiele', cat: 'Eröffnung', text: 'Eröffnungen nach 1.e4 e5, z. B. Italienisch, Spanisch, Königsgambit.', moves: ['e4', 'e5'], lesson: 'o-italienisch' },
  { id: 'halboffene-spiele', term: 'Halboffene Spiele', cat: 'Eröffnung', text: 'Schwarz antwortet auf 1.e4 nicht mit e5, z. B. Sizilianisch, Französisch, Caro-Kann.', moves: ['e4', 'c5'], lesson: 'o-sizilianisch' },
  { id: 'geschlossene-spiele', term: 'Geschlossene Spiele', cat: 'Eröffnung', text: 'Eröffnungen nach 1.d4 d5, etwa das Damengambit.', moves: ['d4', 'd5'], lesson: 'o-damengambit' },
  { id: 'indisch', term: 'Indische Verteidigungen', cat: 'Eröffnung', text: 'Schwarz antwortet auf 1.d4 mit 1…Sf6 und kontrolliert das Zentrum oft von der Seite (Königsindisch, Nimzoindisch, Grünfeld).', moves: ['d4', 'Nf6', 'c4', 'g6'], lesson: 'o-koenigsindisch' },
  { id: 'gambit', term: 'Gambit', cat: 'Eröffnung', text: 'Ein Bauernopfer in der Eröffnung für schnellere Entwicklung oder Zentrumskontrolle.', ex: 'Königsgambit: 2.f4.', moves: ['e4', 'e5', 'f4'], arrows: ['f4e5'] },
  { id: 'hypermodern', term: 'Hypermoderne', cat: 'Eröffnung', text: 'Schule der 1920er (Réti, Nimzowitsch): Das Zentrum nicht besetzen, sondern von der Seite kontrollieren und später angreifen.', ex: 'Königsindisch: Lg7 zielt aufs Zentrum.', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6'], arrows: ['g7d4'] },
  { id: 'eroeffnungsfalle', term: 'Eröffnungsfalle', cat: 'Eröffnung', text: 'Ein naheliegender Zug, der sofort verliert. Beispiel: die Elefantenfalle im Damengambit.', ex: 'Sxd5?? verliert eine Figur.', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'cxd5', 'exd5'], arrows: ['!c3d5'], lesson: 'o-damengambit' },
  { id: 'theorie', term: 'Theorie / Hauptvariante', cat: 'Eröffnung', text: 'Die bekannten, gut analysierten Züge einer Eröffnung. Die Hauptvariante ist die am häufigsten gespielte Fortsetzung.', ex: 'Spanisch, Hauptvariante.', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7'], lesson: 'o-spanisch' },
  { id: 'zugumstellung', term: 'Zugumstellung', cat: 'Eröffnung', text: 'Dieselbe Stellung entsteht über eine andere Zugfolge. Wichtig, um Varianten zu vermeiden oder zu erreichen.', ex: '1.Sf3 d5 2.d4 = 1.d4 d5 2.Sf3.', moves: ['Nf3', 'd5', 'd4'] },
  { id: 'repertoire', term: 'Repertoire', cat: 'Eröffnung', text: 'Die persönliche Auswahl an Eröffnungen, die man mit Weiß und Schwarz spielt.', ex: 'Z. B. London mit Weiß.', moves: ['d4', 'd5', 'Bf4'], lesson: 'o-london' },

  // ───────── Endspiel ─────────
  { id: 'opposition', term: 'Opposition', cat: 'Endspiel', text: 'Die Könige stehen sich mit einem Feld Abstand gegenüber. Wer am Zug ist, muss weichen.', fen: '8/8/4k3/8/4K3/4P3/8/8' + W, hl: ['e4', 'e6'], see: ['zugzwang', 'entfernte-opposition'], lesson: 'e-opposition' },
  { id: 'entfernte-opposition', term: 'Entfernte Opposition', cat: 'Endspiel', text: 'Die Könige stehen mit ungerader Zahl (3 oder 5) Felder Abstand auf einer Linie. Sie lässt sich in die nahe Opposition verwandeln.', fen: '4k3/8/8/8/4K3/8/8/8' + W, hl: ['e4', 'e8'], see: ['opposition'] },
  { id: 'quadratregel', term: 'Quadratregel', cat: 'Endspiel', text: 'Erreicht der König das Quadrat zwischen Bauer und Umwandlungsreihe, holt er den Bauern ein.', fen: '7k/8/8/8/p7/8/8/4K3' + W, arrows: ['a4d4', 'd4d1', 'd1a1'], lesson: 'e-quadrat' },
  { id: 'schluesselfelder', term: 'Schlüsselfelder', cat: 'Endspiel', text: 'Felder, auf denen der König den Bauern immer zur Umwandlung bringt – egal, wer am Zug ist.', ex: 'Für e3: d5, e5, f5.', fen: '4k3/8/8/8/8/4P3/8/4K3' + W, arrows: ['d5', 'e5', 'f5'], lesson: 'e-opposition' },
  { id: 'reservetempo', term: 'Reservetempo', cat: 'Endspiel', text: 'Ein harmloser Zug (meist ein Bauernzug), der die Zugpflicht an den Gegner weitergibt.', ex: 'd2–d3 gewinnt die Opposition.', fen: '8/8/3k4/8/3K4/8/3P4/8' + W, arrows: ['d2d3'], lesson: 'e-opposition' },
  { id: 'lucena', term: 'Lucena-Stellung', cat: 'Endspiel', text: 'Wichtigste Gewinnstellung im Turmendspiel. Methode: König abdrängen, Turm auf die 4. Reihe, Brücke bauen.', fen: '1K1k4/1P6/8/8/8/8/r7/5R2' + W, arrows: ['f1d1', 'd1d4'], see: ['philidor'], lesson: 'e-lucena' },
  { id: 'philidor', term: 'Philidor-Stellung', cat: 'Endspiel', text: 'Wichtigste Remisstellung im Turmendspiel: Turm auf der 3. Reihe, rückt der Bauer vor, Schachs von hinten.', fen: '3k4/R7/8/3PK3/8/8/8/7r' + B, arrows: ['h1h6'], see: ['lucena'], lesson: 'e-philidor' },
  { id: 'falscher-laeufer', term: 'Falscher Läufer', cat: 'Endspiel', text: 'Randbauer + Läufer, der das Umwandlungsfeld nicht beherrscht: Remis, wenn der König in der Ecke steht.', fen: '1k6/8/1K6/P7/8/8/8/2B5' + B, hl: ['a8'], lesson: 'e-falscher-laeufer' },
  { id: 'festung', term: 'Festung', cat: 'Endspiel', text: 'Eine Verteidigungsstellung, die trotz Materialnachteil nicht zu knacken ist.', ex: 'Der König in der Ecke hält remis.', fen: '1k6/8/1K6/P7/8/8/8/2B5' + B, arrows: ['b8a8'] },
  { id: 'aktiver-koenig', term: 'Aktiver König', cat: 'Endspiel', text: 'Im Endspiel wird der König zur Angriffsfigur und gehört ins Zentrum oder zu den Bauern.', ex: 'Capablancas Königsmarsch nach f6.', fen: '5k2/p1p4R/1pr5/3p1pP1/P2P1P2/2P3K1/8/8 b - - 1 35', arrows: ['g3h4', 'h4g5', 'g5f6'] },
  { id: 'turm-hinter-freibauer', term: 'Turm hinter den Freibauern', cat: 'Endspiel', text: 'Tarrasch-Regel: Türme gehören hinter Freibauern – hinter die eigenen und hinter die des Gegners.', ex: 'Ta1 unterstützt den a-Bauern von hinten.', fen: 'r3k3/8/8/P7/8/8/8/R3K3' + W, arrows: ['a1a5'] },
  { id: 'umwandlungsfeld', term: 'Umwandlungsfeld', cat: 'Endspiel', text: 'Das Feld auf der letzten Reihe vor einem Bauern. Seine Farbe entscheidet, welcher Läufer helfen kann.', ex: 'b8 ist dunkel.', fen: '8/5k2/8/8/8/8/1P6/4K3' + W, hl: ['b8'], arrows: ['b2b8'] },
  { id: 'grundmatt', term: 'Grundmatts', cat: 'Endspiel', text: 'Die Standard-Mattführungen mit Dame, Turm, zwei Läufern sowie Läufer und Springer gegen den blanken König.', fen: '8/8/8/4k3/8/8/8/3QK3' + W, arrows: ['d1d4'], lesson: 'e-dame-matt' },
];
