import type { Lesson } from '../types';

// Zugfolgen mit der Lichess-Endspieldatenbank geprüft (Ergebnis bleibt bei jedem Lösungszug erhalten).
export const endspiele3: Lesson[] = [
  {
    id: 'e-reti',
    title: 'Das Réti-Manöver',
    category: 'endspiele',
    level: 3,
    summary: 'Ein König verfolgt zwei Ziele gleichzeitig – die berühmteste Endspielstudie der Welt.',
    fen: '7K/8/k1P5/7p/8/8/8/8 w - - 0 1',
    steps: [
      {
        kind: 'info',
        title: 'Unmöglich?',
        text: {
          short: 'Der schwarze Bauer h5 läuft davon, und dein König steht weit weg. Gleichzeitig ist dein Bauer c6 in Gefahr. Trotzdem hält Weiß Remis!',
          why: 'Richard Réti veröffentlichte diese Studie 1921. Der Trick: Der König geht schräg und kommt so beiden Zielen gleichzeitig näher – auf der Diagonale ist der Weg genauso kurz wie gerade.',
        },
        arrows: ['h8g7', 'g7f6', 'f6e5', 'h5h1'],
      },
      {
        kind: 'move',
        title: 'Diagonal laufen',
        prompt: { short: 'Mit welchem Königszug kommst du dem Bauern h5 UND deinem Bauern c6 näher?', why: 'Gerade nach h7 hilft nur gegen den h-Bauern. Die Diagonale nach g7 hält beide Ziele offen.' },
        solution: ['Kg7'],
        reply: 'h4',
        mistakes: [{ san: 'c7', text: { short: 'Nach 1.c7 Kb7 fällt der Bauer, und der h-Bauer läuft ungestört zur Dame.' } }],
        success: { short: '1.Kg7! h4 – Schwarz läuft weiter.' },
      },
      {
        kind: 'move',
        title: 'Weiter auf der Diagonale',
        prompt: { short: 'Weiter in Richtung beider Ziele.' },
        solution: ['Kf6'],
        reply: 'Kb6',
        success: { short: '2.Kf6 – jetzt erreicht der König das Quadrat des h-Bauern. Schwarz greift deshalb den Bauern c6 an.', why: 'Ginge Schwarz mit 2…h3 weiter, folgt 3.Ke7 h2 4.c7 Kb7 5.Kd7 – beide wandeln um, Remis.' },
      },
      {
        kind: 'move',
        title: 'Der doppelte Zweck',
        prompt: { short: 'Komm deinem Bauern zu Hilfe – und bleib im Quadrat des h-Bauern.' },
        solution: ['Ke5'],
        reply: 'h3',
        success: { short: '3.Ke5! – schlägt Schwarz auf c6, holt dein König den h-Bauern ein (Kf4). Also läuft Schwarz weiter.' },
      },
      {
        kind: 'move',
        title: 'Zur Unterstützung',
        prompt: { short: 'Jetzt unterstütze deinen c-Bauern.' },
        solution: ['Kd6'],
        reply: 'h2',
        success: { short: '4.Kd6 h2 – beide Bauern rennen zur Umwandlung.' },
      },
      {
        kind: 'move',
        title: 'Gleichzeitig ins Ziel',
        prompt: { short: 'Zieh den Bauern vor – er ist gedeckt.' },
        solution: ['c7'],
        reply: 'h1=Q',
        success: { short: '5.c7 h1=D 6.c8=D – beide haben eine Dame: Remis. Der König hat zwei Aufgaben mit einem Weg gelöst.' },
      },
    ],
    takeaways: ['Diagonale Königszüge verfolgen zwei Ziele.', 'Quadratregel: Erreichst du das Quadrat, holst du den Bauern ein.', 'Nicht vorschnell aufgeben – Endspiele sind voller Ressourcen.'],
    pitfalls: ['Gerade laufen statt diagonal.', 'Den eigenen Bauern zu früh vorziehen.'],
    practice: { themes: ['pawnEndgame'] },
  },
  {
    id: 'e-turm-bauer',
    title: 'Turm gegen Bauer',
    category: 'endspiele',
    level: 2,
    summary: 'Der Turm gewinnt – wenn er den gegnerischen König abschneidet und der eigene König rechtzeitig kommt.',
    fen: '8/8/8/8/1pk5/8/K7/1R6 w - - 0 1',
    steps: [
      {
        kind: 'info',
        title: 'Wer ist schneller?',
        text: {
          short: 'Turm gegen Bauer ist meist gewonnen – aber nur, wenn der gegnerische König den Bauern nicht unterstützen kann. Die wichtigste Technik: den König abschneiden.',
          why: 'Ein Turm auf einer Linie oder Reihe ist eine Wand, die der König nicht überqueren darf.',
        },
      },
      {
        kind: 'move',
        title: 'Die Wand',
        prompt: { short: 'Stell den Turm so, dass der schwarze König nicht zur Unterstützung seines Bauern kommt.', why: 'Welche Linie trennt den König vom Bauern? Schachs von weit weg sind auch gut.' },
        solution: ['Rd1', 'Rc1+', 'Rb3', 'Kb2'],
        reply: 'Kc3',
        mistakes: [{ san: 'Rxb4+', text: { short: 'Der Bauer ist gedeckt – nach Kxb4 ist nur noch Remis.' } }],
        success: { short: '1.Td1 – die d-Linie ist gesperrt, der König kann nur noch über c3 vor.' },
      },
      {
        kind: 'move',
        title: 'Der König kommt',
        prompt: { short: 'Bring deinen König vor den Bauern.' },
        solution: ['Kb1', 'Rc1+', 'Rh1', 'Rd5'],
        reply: 'b3',
        success: { short: '2.Kb1 b3 – dein König steht genau vor dem Bauern.' },
      },
      {
        kind: 'move',
        title: 'Abwarten',
        prompt: { short: 'Mach einen Wartezug mit dem Turm, ohne die d-Linie freizugeben.' },
        solution: ['Rd6', 'Rd7', 'Rd8', 'Rh1'],
        reply: 'Kc4',
        success: { short: '3.Td6 – der König darf nicht über die d-Linie, der Bauer kommt nicht weiter.' },
      },
      {
        kind: 'move',
        title: 'Blockieren',
        prompt: { short: 'Greife den Bauern mit dem König an.' },
        solution: ['Kb2'],
        reply: 'Kc5',
        success: { short: '4.Kb2 – der Bauer fällt im nächsten Zug.' },
      },
      {
        kind: 'move',
        title: 'Vorsicht, Gabel!',
        prompt: { short: 'Der schwarze König greift deinen Turm an. Rette ihn – mit Abstand, aber ohne die d-Linie aufzugeben.', why: 'Schlägst du jetzt gierig 5.Kxb3?, folgt Kxd6 – nur noch Remis.' },
        solution: ['Rd3', 'Rd8', 'Rd7', 'Rd1'],
        mistakes: [{ san: 'Kxb3', text: { short: 'Kxd6! – der Turm ist weg, Remis. Erst den Turm sichern, dann den Bauern schlagen.' } }],
        success: { short: 'Richtig – der Turm ist sicher, der Bauer fällt im nächsten Zug. Turm gegen König ist gewonnen.' },
      },
    ],
    takeaways: ['Turm schneidet den König ab.', 'Eigener König vor den Bauern.', 'Wartezüge mit dem Turm, ohne die Wand aufzugeben.'],
    pitfalls: ['Den gedeckten Bauern schlagen.', 'Turm zu nah am gegnerischen König (Gabel- und Schlaggefahr).'],
    practice: { themes: ['rookEndgame'] },
  },
];
