import type { Lesson } from '../types';

export const eroeffnungen2: Lesson[] = [
  {
    id: 'o-schottisch',
    title: 'Schottische Partie',
    category: 'eroeffnungen',
    level: 1,
    summary: 'Sofort das Zentrum öffnen: 3.d4 – klar, direkt und leicht zu lernen.',
    steps: [
      {
        kind: 'info',
        play: ['e4', 'e5', 'Nf3', 'Nc6'],
        text: {
          short: 'Statt Lc4 oder Lb5 öffnet Weiß mit 3.d4 sofort das Zentrum.',
          why: 'Nach dem Abtausch auf d4 steht ein weißer Springer zentral, und Weiß hat freie Figurenentwicklung.',
          pro: 'Kasparow belebte die Schottische Partie in den 1990ern wieder. Sie vermeidet die schwere Theorie der Spanischen Partie.',
        },
      },
      {
        kind: 'move',
        title: 'Zentrum öffnen',
        prompt: { short: 'Greife e5 mit einem Bauern an.' },
        solution: ['d4'],
        reply: 'exd4',
        success: { short: '3.d4 exd4 – Schwarz muss tauschen, sonst verliert er e5.' },
      },
      {
        kind: 'move',
        title: 'Zurückschlagen',
        prompt: { short: 'Hol den Bauern mit einer Figur zurück.' },
        solution: ['Nxd4'],
        reply: 'Nf6',
        mistakes: [{ soft: true, san: 'c3', text: { short: 'Das wäre das Göring-Gambit – spannend, aber heute lernen wir die Hauptvariante 4.Sxd4.' } }],
        success: { short: '4.Sxd4 Sf6 – Schwarz greift e4 an.' },
      },
      {
        kind: 'move',
        title: 'Tausch auf c6',
        prompt: { short: 'Tausche den Springer c6 und schwäche die schwarzen Bauern.' },
        solution: ['Nxc6'],
        reply: 'bxc6',
        success: {
          short: '5.Sxc6 bxc6 – Schwarz hat eine Bauerninsel mehr, aber die offene b-Linie.',
          pro: 'Hauptvariante (Mieses): 6.e5 De7 7.De2 Sd5 8.c4 – scharfe Stellungen, in denen Schwarz aktiv verteidigen muss.',
        },
      },
      {
        kind: 'move',
        title: 'Raum gewinnen',
        prompt: { short: 'Vertreibe den Springer f6 mit einem Bauernzug.' },
        solution: ['e5'],
        reply: 'Qe7',
        success: { short: '6.e5 De7 – die Dame greift e5 an. Weiß deckt mit 7.De2, nach …Sd5 folgt 8.c4 mit Raumvorteil.' },
      },
    ],
    drill: [{ name: 'Mieses-Variante', color: 'white', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nxc6', 'bxc6', 'e5', 'Qe7', 'Qe2', 'Nd5', 'c4'] }],
    takeaways: ['3.d4 öffnet sofort das Zentrum.', 'Sxc6 schwächt die schwarze Bauernstruktur.'],
  },
  {
    id: 'o-evans',
    title: 'Evansgambit',
    category: 'eroeffnungen',
    level: 2,
    summary: 'Ein Bauer für Tempo und ein mächtiges Zentrum – Morphys und Kasparows Waffe.',
    steps: [
      {
        kind: 'info',
        play: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'],
        text: {
          short: 'Italienische Partie – aber jetzt opfert Weiß einen Bauern, um c3 und d4 mit Tempo zu spielen.',
          why: 'Nimmt Schwarz auf b4, gewinnt Weiß mit c3 ein Tempo gegen den Läufer und baut das Zentrum auf.',
          pro: 'Captain Evans erfand das Gambit um 1827. Kasparow besiegte damit 1995 Anand in 25 Zügen.',
        },
        arrows: ['b2b4', 'c5b4'],
      },
      {
        kind: 'move',
        title: 'Das Gambit',
        prompt: { short: 'Biete den b-Bauern an!' },
        solution: ['b4'],
        reply: 'Bxb4',
        success: { short: '4.b4 Lxb4 – Schwarz nimmt an.' },
      },
      {
        kind: 'move',
        title: 'Tempo gegen den Läufer',
        prompt: { short: 'Greife den Läufer an und bereite d4 vor.' },
        solution: ['c3'],
        reply: 'Ba5',
        success: { short: '5.c3 La5 – jetzt folgt d4 mit starkem Zentrum.' },
      },
      {
        kind: 'move',
        title: 'Das Zentrum',
        prompt: { short: 'Besetze das Zentrum.' },
        solution: ['d4'],
        reply: 'exd4',
        mistakes: [{ soft: true, san: 'O-O', text: { short: 'Auch spielbar, aber d4 nutzt das gewonnene Tempo sofort.' } }],
        success: { short: '6.d4 exd4 7.O-O – Weiß ist weit voraus in der Entwicklung.' },
      },
      {
        kind: 'move',
        title: 'Rochade',
        prompt: { short: 'Bring den König in Sicherheit und öffne die e-Linie für den Turm.' },
        solution: ['O-O'],
        success: {
          short: '7.O-O – ein Bauer weniger, aber zwei Tempi mehr und offene Linien gegen den schwarzen König.',
          pro: 'Typisch für Gambits: Material gegen Zeit. Wer das Gambit spielt, muss schnell angreifen, bevor Schwarz sich konsolidiert.',
        },
      },
    ],
    drill: [{ name: 'Hauptvariante', color: 'white', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4', 'Bxb4', 'c3', 'Ba5', 'd4', 'exd4', 'O-O'] }],
    takeaways: ['Bauer gegen Tempo und Zentrum.', 'c3 und d4 mit Tempo.', 'Schnell angreifen.'],
  },
  {
    id: 'o-koenigsgambit',
    title: 'Königsgambit',
    category: 'eroeffnungen',
    level: 3,
    summary: 'Die romantischste Eröffnung: f4! – für Angriff, Linien und Abenteuer.',
    steps: [
      {
        kind: 'move',
        title: 'Das Gambit',
        play: ['e4', 'e5'],
        prompt: {
          short: 'Biete den f-Bauern an, um das schwarze Zentrum zu beseitigen und die f-Linie zu öffnen.',
          why: 'Nach …exf4 hat Weiß ein Übergewicht im Zentrum (d4 folgt) und die halboffene f-Linie.',
        },
        solution: ['f4'],
        reply: 'exf4',
        success: { short: '2.f4 exf4 – das angenommene Königsgambit.' },
      },
      {
        kind: 'move',
        title: 'Den Königsspringer entwickeln',
        prompt: { short: 'Verhindere …Dh4+ und entwickle.' },
        solution: ['Nf3'],
        reply: 'g5',
        mistakes: [{ soft: true, san: 'Bc4', text: { short: 'Das Läufergambit ist spielbar, aber nach …Dh4+ muss der König ziehen – wie in der Unsterblichen Partie.' } }],
        success: { short: '3.Sf3 g5 – Schwarz verteidigt den Mehrbauern.' },
      },
      {
        kind: 'move',
        title: 'Den Bauernkeil angreifen',
        prompt: { short: 'Greife den Bauern g5 an und zerstöre die schwarze Bauernkette.' },
        solution: ['h4'],
        reply: 'g4',
        success: { short: '4.h4 g4 5.Se5 – das Kieseritzky-Gambit: Der Springer steht mitten im Brett.' },
      },
      {
        kind: 'move',
        title: 'Der Springer springt',
        prompt: { short: 'Der Springer wird angegriffen – wohin, und zwar aktiv?' },
        solution: ['Ne5'],
        mistakes: [{ san: 'Ng5', text: { short: 'Nach …h6 ist der Springer verloren, oder Weiß muss auf f7 opfern (Allgaier-Gambit – sehr riskant).' }, soft: true }],
        success: {
          short: '5.Se5 – das Kieseritzky-Gambit. Der Springer steht zentral und zielt auf f7 und g4.',
          pro: 'Spassky schlug Fischer 1960 mit dem Königsgambit – und Fischer schrieb danach „A Bust to the King’s Gambit“. Heute gilt es als spielbar, aber riskant.',
        },
      },
    ],
    drill: [{ name: 'Kieseritzky', color: 'white', moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'g5', 'h4', 'g4', 'Ne5', 'Nf6', 'd4', 'd6', 'Nd3'] }],
    takeaways: ['f4 für Zentrum und f-Linie.', 'Sf3 verhindert …Dh4+.', 'Aggressiv spielen – Material zählt weniger.'],
    pitfalls: ['Den König zu lange in der Mitte lassen.', 'Nach …Dh4+ in Panik geraten.'],
  },
  {
    id: 'o-englisch',
    title: 'Englische Eröffnung',
    category: 'eroeffnungen',
    level: 2,
    summary: '1.c4 – Kontrolle über d5 von der Flanke, flexibel und strategisch.',
    steps: [
      {
        kind: 'move',
        title: '1.c4',
        prompt: {
          short: 'Kontrolliere das Feld d5 mit einem Flügelbauern.',
          why: 'Die Englische Eröffnung ist wie ein umgekehrter Sizilianer: Weiß greift das Zentrum von der Seite an.',
        },
        solution: ['c4'],
        reply: 'e5',
        success: { short: '1.c4 e5 – Sizilianisch mit vertauschten Farben und einem Tempo mehr für Weiß.' },
      },
      {
        kind: 'move',
        title: 'Druck auf d5',
        prompt: { short: 'Entwickle den Damenspringer.' },
        solution: ['Nc3'],
        reply: 'Nf6',
        success: { short: '2.Sc3 Sf6 – beide kämpfen um d5.' },
      },
      {
        kind: 'move',
        title: 'Das Fianchetto',
        prompt: { short: 'Bereite das Fianchetto des Königsläufers vor.' },
        solution: ['g3'],
        reply: 'd5',
        success: { short: '3.g3 d5 – Schwarz besetzt das Zentrum, der Läufer g2 wird darauf zielen.' },
      },
      {
        kind: 'move',
        title: 'Zentrum aufbrechen',
        prompt: { short: 'Tausche den c-Bauern gegen den Zentrumsbauern d5.' },
        solution: ['cxd5'],
        reply: 'Nxd5',
        success: { short: '4.cxd5 Sxd5 5.Lg2 – der Läufer auf der langen Diagonale übt Druck auf d5 und b7 aus.' },
      },
      {
        kind: 'move',
        title: 'Der Läufer auf g2',
        prompt: { short: 'Vollende das Fianchetto.' },
        solution: ['Bg2'],
        success: {
          short: '5.Lg2 – typische Englisch-Struktur. Weiß spielt am Damenflügel mit Tb1, b4, b5.',
          pro: 'Das ist die Umkehrung des Drachen-Sizilianers. Weiß hat ein Tempo mehr – und nutzt es für den Damenflügelangriff.',
        },
        successArrows: ['g2b7'],
      },
    ],
    drill: [{ name: 'Umgekehrter Drache', color: 'white', moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'd5', 'cxd5', 'Nxd5', 'Bg2', 'Nb6', 'Nf3', 'Nc6', 'O-O', 'Be7'] }],
    takeaways: ['1.c4 kontrolliert d5 von der Flanke.', 'Fianchetto mit Lg2.', 'Plan: Damenflügel (Tb1, b4).'],
  },
  {
    id: 'o-slawisch',
    title: 'Slawische Verteidigung',
    category: 'eroeffnungen',
    level: 2,
    orientation: 'black',
    summary: 'Gegen das Damengambit: d5 mit c6 stützen – und den Läufer c8 frei behalten.',
    steps: [
      {
        kind: 'move',
        title: '…c6',
        play: ['d4', 'd5', 'c4'],
        prompt: {
          short: 'Stütze d5 mit einem Bauernzug, der den Läufer c8 NICHT einsperrt.',
          why: 'Im Gegensatz zu …e6 (Abgelehntes Damengambit) bleibt die Diagonale c8–h3 offen.',
        },
        solution: ['c6'],
        reply: 'Nf3',
        mistakes: [{ soft: true, san: 'e6', text: { short: 'Auch solide (Abgelehntes Damengambit), aber der Läufer c8 wird eingesperrt.' } }],
        success: { short: '2…c6 3.Sf3 – die Slawische Verteidigung.' },
      },
      {
        kind: 'move',
        title: 'Entwicklung',
        prompt: { short: 'Entwickle den Königsspringer.' },
        solution: ['Nf6'],
        reply: 'Nc3',
        success: { short: '3…Sf6 4.Sc3 – jetzt der typische Slawisch-Zug.' },
      },
      {
        kind: 'move',
        title: 'Den Bauern nehmen',
        prompt: {
          short: 'Nimm den Bauern c4 – Weiß wird ihn zurückgewinnen, aber Schwarz gewinnt Zeit für …Lf5.',
        },
        solution: ['dxc4'],
        reply: 'a4',
        success: { short: '4…dxc4 5.a4 – Weiß verhindert …b5, mit dem Schwarz den Bauern halten würde.' },
      },
      {
        kind: 'move',
        title: 'Der befreite Läufer',
        prompt: { short: 'Entwickle den Läufer c8 auf seine beste Diagonale.' },
        solution: ['Bf5'],
        success: {
          short: '5…Lf5 – das ist der Sinn von Slawisch: Der Läufer ist draußen, bevor …e6 folgt.',
          pro: 'Hauptlinie: 6.e3 e6 7.Lxc4 Lb4 8.O-O O-O – solide und strategisch gesund für Schwarz.',
        },
      },
    ],
    drill: [{ name: 'Hauptvariante', color: 'black', moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'a4', 'Bf5', 'e3', 'e6', 'Bxc4', 'Bb4', 'O-O', 'O-O'] }],
    takeaways: ['…c6 stützt d5 ohne den Läufer einzusperren.', '…dxc4 und …Lf5.'],
  },
  {
    id: 'o-nimzoindisch',
    title: 'Nimzoindische Verteidigung',
    category: 'eroeffnungen',
    level: 3,
    orientation: 'black',
    summary: 'Nimzowitschs Meisterwerk: Fesselung, Doppelbauern und Kampf um e4.',
    steps: [
      {
        kind: 'info',
        play: ['d4', 'Nf6', 'c4', 'e6', 'Nc3'],
        text: {
          short: 'Weiß will e4 spielen und das Zentrum beherrschen. Schwarz verhindert das mit einer Fesselung.',
          why: 'Der Springer c3 kontrolliert e4. Wird er gefesselt (oder getauscht), fehlt Weiß die Kontrolle über e4.',
          pro: 'Die Nimzoindische ist eine der angesehensten Eröffnungen überhaupt – gespielt von Weltmeistern wie Capablanca, Botwinnik, Karpow, Kasparow und Carlsen.',
        },
        arrows: ['c3e4', 'f6e4'],
      },
      {
        kind: 'move',
        title: 'Die Fesselung',
        prompt: { short: 'Fessele den Springer c3 an den König.' },
        solution: ['Bb4'],
        reply: 'e3',
        success: { short: '3…Lb4 – die Nimzoindische. 4.e3 (Rubinstein) ist das solideste System.' },
        successArrows: ['b4e1'],
      },
      {
        kind: 'move',
        title: 'Rochade',
        prompt: { short: 'Bring den König in Sicherheit.' },
        solution: ['O-O'],
        reply: 'Bd3',
        success: { short: '4…O-O 5.Ld3 – jetzt greift Schwarz das Zentrum an.' },
      },
      {
        kind: 'move',
        title: 'Zentrumsschlag',
        prompt: { short: 'Greife d4 an.' },
        solution: ['d5', 'c5'],
        reply: 'Nf3',
        success: {
          short: '5…d5 (oder …c5) – Schwarz kämpft um das Zentrum.',
          pro: 'Nimmt Schwarz später auf c3 (…Lxc3 bxc3), bekommt Weiß das Läuferpaar, aber Doppelbauern auf c3/c4 – ein typisches Ungleichgewicht der Nimzoindischen.',
        },
      },
    ],
    drill: [{ name: 'Rubinstein-System', color: 'black', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5', 'Nf3', 'c5', 'O-O', 'Nc6'] }],
    takeaways: ['…Lb4 fesselt und kämpft um e4.', 'Läuferpaar gegen Doppelbauern.'],
  },
  {
    id: 'o-drache',
    title: 'Sizilianisch: Drachenvariante',
    category: 'eroeffnungen',
    level: 3,
    orientation: 'black',
    summary: 'Der Läufer g7 als Feuerspeier auf der langen Diagonale – scharf und gefährlich.',
    steps: [
      {
        kind: 'info',
        play: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3'],
        text: {
          short: 'Offene Sizilianische Partie. Im Drachen fianchettiert Schwarz den Läufer auf g7 – die schwarze Bauernkette erinnert an ein Drachensternbild.',
          why: 'Der Läufer g7 zielt über die lange Diagonale auf d4, c3 und b2 – ideal für einen Damenflügelangriff.',
          pro: 'Gegen den Jugoslawischen Angriff (Le3, f3, Dd2, O-O-O, h4–h5) wird es extrem scharf: Beide Seiten stürmen auf den König.',
        },
        arrows: ['g7b2'],
      },
      {
        kind: 'move',
        title: 'Das Fianchetto',
        prompt: { short: 'Bereite den Drachen-Läufer vor.' },
        solution: ['g6'],
        reply: 'Be3',
        success: { short: '5…g6 6.Le3 – Weiß plant den Jugoslawischen Angriff.' },
      },
      {
        kind: 'move',
        title: 'Der Drache',
        prompt: { short: 'Stell den Läufer auf die lange Diagonale.' },
        solution: ['Bg7'],
        reply: 'f3',
        success: { short: '6…Lg7 7.f3 – Weiß sichert e4 und bereitet g4 vor.' },
      },
      {
        kind: 'move',
        title: 'Rochade',
        prompt: { short: 'Rochiere – der König steht hinter dem Drachen sicher.' },
        solution: ['O-O'],
        reply: 'Qd2',
        success: { short: '7…O-O 8.Dd2 – jetzt …Sc6 und der Angriff auf den Damenflügel.' },
      },
      {
        kind: 'move',
        title: 'Entwicklung mit Druck',
        prompt: { short: 'Entwickle den letzten Springer mit Druck auf d4.' },
        solution: ['Nc6'],
        success: {
          short: '8…Sc6 – Schwarz plant …Ld7, …Tc8, …Se5–c4 und oft das Qualitätsopfer …Txc3!',
          pro: 'Das Qualitätsopfer auf c3 ist das Markenzeichen des Drachen: Es zerstört die weiße Königsstellung und macht den Läufer g7 noch stärker.',
        },
      },
    ],
    drill: [{ name: 'Jugoslawischer Angriff', color: 'black', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Be3', 'Bg7', 'f3', 'O-O', 'Qd2', 'Nc6', 'Bc4', 'Bd7', 'O-O-O', 'Rc8'] }],
    takeaways: ['Läufer g7 auf der langen Diagonale.', 'Qualitätsopfer …Txc3 als typische Idee.', 'Rennen der Angriffe.'],
  },
  {
    id: 'o-hollaendisch',
    title: 'Holländische Verteidigung',
    category: 'eroeffnungen',
    level: 3,
    orientation: 'black',
    summary: '1…f5 gegen 1.d4: Kontrolle über e4 und Königsangriff – ein unausgeglichener Kampf.',
    steps: [
      {
        kind: 'move',
        title: '1…f5',
        play: ['d4'],
        prompt: {
          short: 'Kontrolliere das Feld e4 mit dem f-Bauern.',
          why: 'Wie Sizilianisch gegen 1.e4: Schwarz schafft sofort ein Ungleichgewicht.',
        },
        solution: ['f5'],
        reply: 'g3',
        success: { short: '1…f5 2.g3 – Weiß fianchettiert und zielt auf die geschwächte Diagonale.' },
      },
      {
        kind: 'move',
        title: 'Entwicklung',
        prompt: { short: 'Entwickle den Königsspringer – er unterstützt die Kontrolle über e4.' },
        solution: ['Nf6'],
        reply: 'Bg2',
        success: { short: '2…Sf6 3.Lg2 – jetzt wählt Schwarz einen Aufbau.' },
      },
      {
        kind: 'move',
        title: 'Leningrader System',
        prompt: { short: 'Spiele das Leningrader System: Fianchetto wie im Königsindischen.' },
        solution: ['g6'],
        reply: 'Nf3',
        mistakes: [{ soft: true, san: 'e6', text: { short: 'Das führt zum klassischen oder Stonewall-System – ebenfalls gut. Heute lernen wir das Leningrader System.' } }],
        success: { short: '3…g6 4.Sf3 Lg7 – das Leningrader System, dynamisch und aggressiv.' },
      },
      {
        kind: 'move',
        title: 'Der Läufer',
        prompt: { short: 'Vollende das Fianchetto.' },
        solution: ['Bg7'],
        success: {
          short: '4…Lg7 – Schwarz rochiert, spielt …d6 und …e5. Achtung: Die Diagonale e8–h5 ist geschwächt!',
          pro: 'Typischer Fehler im Holländischen: zu früh …Lg7 ohne Rochade, dann Dh5+ oder Lh5+-Tricks. Und gegen 2.Lg5 oder das Staunton-Gambit (2.e4) braucht man Vorbereitung.',
        },
      },
    ],
    drill: [{ name: 'Leningrader System', color: 'black', moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'g6', 'Nf3', 'Bg7', 'O-O', 'O-O', 'c4', 'd6', 'Nc3', 'Qe8'] }],
    takeaways: ['…f5 kontrolliert e4.', 'Achtung auf die Diagonale e8–h5.'],
  },
];
