import type { Lesson } from '../types';

export const eroeffnungen: Lesson[] = [
  {
    id: 'o-italienisch',
    title: 'Italienische Partie',
    category: 'eroeffnungen',
    level: 1,
    summary: 'Die klassische Eröffnung: schnelle Entwicklung, Druck auf f7, Plan c3 und d4.',
    steps: [
      {
        kind: 'move',
        title: '1. Zug',
        prompt: { short: 'Beginne mit dem Königsbauern zwei Felder.' },
        solution: ['e4'],
        reply: 'e5',
        success: { short: '1.e4 e5 – beide Seiten besetzen das Zentrum.' },
      },
      {
        kind: 'move',
        title: 'Angriff auf e5',
        prompt: { short: 'Entwickle mit Angriff auf den Bauern e5.' },
        solution: ['Nf3'],
        reply: 'Nc6',
        mistakes: [
          { soft: true, san: 'Bc4', text: { short: 'Auch spielbar (Läuferspiel), aber erst Sf3 entwickelt mit Tempo – Schwarz muss e5 decken.' } },
        ],
        success: { short: '2.Sf3 Sc6 – Schwarz deckt e5 und entwickelt ebenfalls.' },
      },
      {
        kind: 'move',
        title: 'Der italienische Läufer',
        prompt: {
          short: 'Stell den Läufer auf die Diagonale zum schwächsten Punkt f7.',
          why: 'Das ist der Zug, der der Eröffnung ihren Namen gibt (Giuoco Piano – „ruhiges Spiel“).',
        },
        solution: ['Bc4'],
        reply: 'Bc5',
        success: {
          short: '3.Lc4 Lc5 – symmetrisch. Beide Läufer zielen auf den schwachen Bauern f2/f7.',
          pro: 'Nach 3…Sf6 entsteht das Zweispringerspiel. 4.Sg5 greift f7 an – nach 4…d5 5.exd5 muss Schwarz genau spielen (5…Sa5!), denn 5…Sxd5?! 6.Sxf7!? ist der gefürchtete „Fried Liver“-Angriff.',
        },
        successArrows: ['c4f7', '?c5f2'],
      },
      {
        kind: 'move',
        title: 'Den Plan vorbereiten',
        prompt: {
          short: 'Weiß möchte d4 spielen und das Zentrum übernehmen. Welcher Bauernzug bereitet das vor?',
          why: 'Ein Bauer muss d4 unterstützen, damit nach …exd4 zurückgeschlagen werden kann.',
        },
        solution: ['c3'],
        reply: 'Nf6',
        mistakes: [
          { soft: true, san: 'd4', text: { short: 'Sofort 4.d4 exd4 lässt das Zentrum ohne Bauernstütze – Weiß kann nicht mit einem Bauern zurückschlagen.' } },
          { soft: true, san: 'Nc3', text: { short: 'Sc3 ist solide, verhindert aber c3 – ohne c3 fehlt die Unterstützung für d4.' } },
        ],
        success: {
          short: '4.c3! bereitet d4 vor. Schwarz entwickelt mit Angriff auf e4.',
          pro: 'Moderne Großmeister spielen oft 4.c3 mit 5.d3 („Giuoco Pianissimo“): ruhiger Aufbau, später d3–d4 oder ein Königsangriff mit Sbd2–f1–g3.',
        },
        successArrows: ['c3d4'],
      },
      {
        kind: 'move',
        title: 'Ruhig und solide',
        prompt: {
          short: 'Decke den Bauern e4 mit einem Bauernzug.',
          why: 'Der Springer f6 greift e4 an. Der moderne Zug stützt e4 und öffnet den Läufer c1.',
        },
        solution: ['d3'],
        reply: 'd6',
        success: { short: '5.d3 d6 – eine ruhige, strategisch reiche Stellung. Weiß rochiert, stellt den Turm nach e1 und manövriert.' },
      },
      {
        kind: 'move',
        title: 'Rochade',
        prompt: { short: 'Bring den König in Sicherheit.' },
        solution: ['O-O'],
        reply: 'O-O',
        success: { short: 'Beide Seiten haben rochiert. Typische Pläne für Weiß: Te1, Sbd2–f1–g3, a4 (Raum am Damenflügel) und Lb3.' },
      },
      {
        kind: 'info',
        title: 'Typische Fehler',
        text: {
          short: '1) Den Läufer c4 mit …Sa5 abtauschen lassen, ohne Rückzug (Lb3 vorher!). 2) Zu früh Sg5 spielen, bevor Schwarz f7 aufgibt. 3) d4 ohne c3 – das Zentrum bricht zusammen.',
          why: 'Die Italienische Partie ist ruhig – wer ungeduldig angreift, hat oft schlechtere Figuren, wenn der Angriff verpufft.',
          pro: 'Theorie-Hinweis: Nach 5…d6 6.O-O O-O 7.Te1 a6 8.Lb3 La7 9.h3 ist eine der Haupttabien der Weltspitze. Carlsen und Caruana haben hier hunderte Partien gespielt.',
        },
        arrows: ['a2a4', 'f1e1', 'b1d2'],
      },
    ],
    drill: [
      { name: 'Giuoco Pianissimo', color: 'white', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd3', 'd6', 'O-O', 'O-O', 'Re1', 'a6', 'Bb3', 'Ba7', 'h3'] },
      { name: 'Zweispringerspiel 4.d3', color: 'white', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'd3', 'Be7', 'O-O', 'O-O', 'Re1', 'd6', 'c3'] },
    ],
    takeaways: ['Lc4 zielt auf f7.', 'c3 bereitet d4 vor.', 'Modern: d3, Te1, Sbd2–f1–g3.'],
    pitfalls: ['d4 ohne c3.', 'Zu früher, unvorbereiteter Angriff mit Sg5.'],
  },
  {
    id: 'o-london',
    title: 'Londoner System',
    category: 'eroeffnungen',
    level: 1,
    summary: 'Ein Aufbau gegen fast alles: d4, Lf4, e3, Sf3, c3 – mit klaren Plänen.',
    steps: [
      {
        kind: 'move',
        title: '1. Zug',
        prompt: { short: 'Beginne mit dem Damenbauern.' },
        solution: ['d4'],
        reply: 'd5',
        success: { short: '1.d4 d5.' },
      },
      {
        kind: 'move',
        title: 'Der London-Läufer',
        prompt: {
          short: 'Entwickle den Läufer c1 – BEVOR du e3 spielst!',
          why: 'Nach e3 wäre der Läufer c1 eingesperrt. Deshalb kommt er zuerst heraus.',
        },
        solution: ['Bf4'],
        reply: 'Nf6',
        mistakes: [
          { soft: true, san: 'e3', text: { short: 'Jetzt ist der Läufer c1 hinter e3 eingesperrt – genau das will das Londoner System vermeiden.' } },
        ],
        success: { short: '2.Lf4 – der Markenzeichen-Zug des Londoner Systems.' },
      },
      {
        kind: 'move',
        title: 'Die Pyramide',
        prompt: { short: 'Stütze d4 und öffne den Läufer f1.' },
        solution: ['e3'],
        reply: 'e6',
        success: { short: '3.e3 – jetzt ist d4 fest und der Läufer f1 kann nach d3.' },
      },
      {
        kind: 'move',
        title: 'Entwicklung',
        prompt: { short: 'Entwickle den Königsspringer.' },
        solution: ['Nf3'],
        reply: 'c5',
        success: { short: '4.Sf3 c5 – Schwarz greift das Zentrum an. Wie reagiert Weiß?' },
      },
      {
        kind: 'move',
        title: 'Die Pyramide vollenden',
        prompt: {
          short: 'Stütze d4 ein zweites Mal.',
          why: 'Nach …cxd4 soll ein Bauer zurückschlagen können – so bleibt das Zentrum stabil.',
        },
        solution: ['c3'],
        reply: 'Nc6',
        success: { short: '5.c3 – die typische London-Pyramide c3–d4–e3.' },
      },
      {
        kind: 'move',
        title: 'Den Springer entwickeln',
        prompt: { short: 'Entwickle den Damenspringer – aber so, dass er c3 nicht blockiert.' },
        solution: ['Nbd2'],
        reply: 'Bd6',
        mistakes: [
          { san: 'Na3', text: { short: 'Am Rand ist der Springer schwach. Über d2 kann er später nach f3 oder e5 unterstützen.' }, soft: true },
        ],
        success: { short: '6.Sbd2 Ld6 – Schwarz bietet den Läuferabtausch an.' },
      },
      {
        kind: 'move',
        title: 'Läuferabtausch vermeiden',
        prompt: {
          short: 'Der schwarze Läufer d6 greift deinen Läufer f4 an. Was tust du?',
          why: 'Nach Lxd6 Dxd6 hätte Schwarz seinen „schlechten“ Läufer losgeworden. Weiß möchte den Läufer behalten.',
        },
        solution: ['Bg3'],
        reply: 'O-O',
        mistakes: [
          { soft: true, san: 'Bxd6', text: { short: 'Nicht schlecht, aber du hilfst Schwarz: Sein Läufer d6 war der schwächere, jetzt ist er getauscht.' } },
        ],
        success: {
          short: '7.Lg3! Wenn Schwarz auf g3 tauscht, öffnet hxg3 die h-Linie für den weißen Turm.',
          pro: 'Moderne Alternative: 7.Lb5 mit Druck auf c6 oder das Jobava-London mit Sc3.',
        },
      },
      {
        kind: 'info',
        title: 'Plan und Falle',
        text: {
          short: 'Plan für Weiß: Ld3, O-O, De2, Se5 und oft f4 mit Königsangriff (Stonewall-Idee).',
          why: 'Typischer Fehler für Weiß: Den Bauern b2 vergessen. Nach …Db6 hängt b2 – der Zug Db3 oder Dc1 schützt ihn.',
          pro: 'Die berühmte Falle im London: 1.d4 d5 2.Lf4 c5 3.e3 Db6?! 4.Sc3! Dxb2?? 5.Sb5 – droht Sc7+ und Tb1, die Dame ist in Gefahr.',
        },
        arrows: ['f1d3', 'f3e5', 'f2f4'],
      },
    ],
    drill: [
      { name: 'Hauptlinie mit …c5', color: 'white', moves: ['d4', 'd5', 'Bf4', 'Nf6', 'e3', 'e6', 'Nf3', 'c5', 'c3', 'Nc6', 'Nbd2', 'Bd6', 'Bg3', 'O-O', 'Bd3'] },
      { name: 'Gegen Königsindisch', color: 'white', moves: ['d4', 'Nf6', 'Bf4', 'g6', 'e3', 'Bg7', 'Nf3', 'O-O', 'Be2', 'd6', 'h3', 'c5', 'c3'] },
    ],
    takeaways: ['Lf4 VOR e3.', 'Pyramide c3–d4–e3.', 'Gegen …Ld6: Lg3.'],
    pitfalls: ['b2 unbewacht lassen gegen …Db6.', 'Zu passiv spielen – das London braucht einen Plan (Se5, f4).'],
  },
  {
    id: 'o-skandinavisch',
    title: 'Skandinavische Verteidigung',
    category: 'eroeffnungen',
    level: 1,
    orientation: 'black',
    summary: 'Sofort 1…d5: Schwarz fordert das Zentrum heraus. Einfach zu lernen, solide zu spielen.',
    steps: [
      {
        kind: 'info',
        play: ['e4'],
        text: {
          short: 'Weiß beginnt mit 1.e4. Mit 1…d5 greift Schwarz den Bauern sofort an.',
          why: 'Die Idee: Schwarz zwingt einen frühen Abtausch und bekommt eine klare, stabile Stellung.',
        },
      },
      {
        kind: 'move',
        title: 'Der Konter',
        prompt: { short: 'Greife e4 sofort an!' },
        solution: ['d5'],
        reply: 'exd5',
        success: { short: '1…d5 2.exd5 – jetzt schlägt Schwarz zurück.' },
      },
      {
        kind: 'move',
        title: 'Zurückschlagen',
        prompt: { short: 'Hol den Bauern mit der Dame zurück.' },
        solution: ['Qxd5'],
        reply: 'Nc3',
        mistakes: [
          { soft: true, san: 'Nf6', text: { short: '2…Sf6 ist die „Moderne Variante“ – auch spielbar, aber heute lernen wir 2…Dxd5.' } },
        ],
        success: { short: '2…Dxd5 3.Sc3 – Weiß greift die Dame mit Tempo an. Wohin mit ihr?' },
      },
      {
        kind: 'move',
        title: 'Die Dame in Sicherheit',
        prompt: {
          short: 'Wähle ein gutes Feld für die Dame.',
          why: 'Die Dame soll aktiv, aber sicher stehen. Von a5 fesselt sie oft den Springer c3 und behält die Diagonale.',
        },
        solution: ['Qa5', 'Qd6', 'Qd8'],
        reply: 'd4',
        mistakes: [
          { san: 'Qe5+', text: { short: '…De5+ sieht aktiv aus, aber nach Le2 wird die Dame mit d4 oder Sf3 weiter gejagt. Zeitverlust!' }, soft: true },
          { san: 'Qe6+', text: { short: 'Die Dame blockiert den Läufer c8 und den Bauern e7 – eine schlechte Stellung.' }, soft: true },
        ],
        success: {
          short: '3…Da5 – die klassische Aufstellung. 3…Dd6 und 3…Dd8 sind ebenfalls Haupvarianten.',
          pro: 'Die Da5-Stellung ähnelt einer Caro-Kann-Struktur mit c6, Lf5, e6 – nur mit aktiverer Dame.',
        },
      },
      {
        kind: 'move',
        title: 'Entwicklung',
        prompt: { short: 'Entwickle den Königsspringer.' },
        solution: ['Nf6'],
        reply: 'Nf3',
        success: { short: '4…Sf6 5.Sf3 – nun folgt der typische Aufbau.' },
      },
      {
        kind: 'move',
        title: 'Rückzugsfeld für die Dame',
        prompt: {
          short: 'Schaffe der Dame ein Rückzugsfeld und bereite …Lf5 vor.',
          why: 'Ein kleiner Bauernzug gibt der Dame das Feld c7 und kontrolliert b5 und d5.',
        },
        solution: ['c6'],
        reply: 'Bc4',
        success: { short: '5…c6 – jetzt kommt der Läufer nach f5, danach …e6. Solide wie ein Fels.' },
      },
      {
        kind: 'move',
        title: 'Der gute Läufer',
        prompt: { short: 'Entwickle den Läufer c8 VOR …e6.' },
        solution: ['Bf5'],
        reply: 'Bd2',
        mistakes: [
          { soft: true, san: 'e6', text: { short: 'Jetzt ist der Läufer c8 eingesperrt. Erst Lf5, dann e6!' } },
        ],
        success: { short: '6…Lf5 7.Ld2 – Weiß droht Sd5 mit Abzug auf die Dame a5. Schwarz spielt …e6 und steht gut.' },
      },
    ],
    drill: [
      { name: 'Hauptlinie 3…Da5', color: 'black', moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'd4', 'Nf6', 'Nf3', 'c6', 'Bc4', 'Bf5', 'Bd2', 'e6'] },
    ],
    takeaways: ['1…d5 und 2…Dxd5.', 'Dame nach a5/d6/d8.', 'Erst …Lf5, dann …e6.'],
    pitfalls: ['Die Dame zu oft ziehen.', 'Den Läufer c8 mit …e6 einsperren.'],
  },
  {
    id: 'o-spanisch',
    title: 'Spanische Partie',
    category: 'eroeffnungen',
    level: 2,
    summary: 'Die „Königin der Eröffnungen“: indirekter Druck auf e5 und ein langer, strategischer Kampf.',
    steps: [
      {
        kind: 'info',
        play: ['e4', 'e5', 'Nf3', 'Nc6'],
        text: {
          short: 'Nach 1.e4 e5 2.Sf3 Sc6 greift Weiß den Verteidiger von e5 an.',
          why: 'Der Springer c6 schützt e5. Wenn er abgetauscht wird, ist e5 schwächer.',
        },
      },
      {
        kind: 'move',
        title: 'Der spanische Läufer',
        prompt: { short: 'Greife den Verteidiger von e5 an.' },
        solution: ['Bb5'],
        reply: 'a6',
        success: {
          short: '3.Lb5 a6 – die Morphy-Verteidigung. Schwarz fragt den Läufer sofort.',
          pro: 'Nach 3…Sf6 kommt die Berliner Mauer (4.O-O Sxe4), mit der Kramnik 2000 Kasparow entthronte.',
        },
        successArrows: ['b5c6', 'c6e5'],
      },
      {
        kind: 'move',
        title: 'Rückzug oder Tausch?',
        prompt: {
          short: 'Der Läufer wird angegriffen. Behalte ihn und die Spannung!',
          why: 'Der Läufer möchte langfristig auf der Diagonale a4–e8 bzw. b3–f7 bleiben.',
        },
        solution: ['Ba4'],
        reply: 'Nf6',
        mistakes: [
          {
            soft: true,
            san: 'Bxc6',
            text: {
              short: 'Die Abtauschvariante ist spielbar – aber Achtung: Nach 4…dxc6 5.Sxe5? Dd4! bekommt Schwarz den Bauern zurück.',
              why: 'Die Dame greift e5 und e4 gleichzeitig an. Der Bauer e5 ist also noch gar nicht „frei“.',
            },
          },
        ],
        success: { short: '4.La4 Sf6 – Schwarz greift e4 an.' },
      },
      {
        kind: 'move',
        title: 'Rochade trotz e4',
        prompt: {
          short: 'Rochiere – der Bauer e4 ist nur scheinbar in Gefahr.',
          why: 'Nach …Sxe4 öffnet Te1 die e-Linie, und Weiß gewinnt den Bauern meist zurück.',
        },
        solution: ['O-O'],
        reply: 'Be7',
        mistakes: [
          { soft: true, san: 'Nc3', text: { short: 'Spielbar (Vierspringerspiel-Charakter), aber die Rochade ist aktiver und typischer.' } },
        ],
        success: { short: '5.O-O Le7 – die geschlossene Spanische Partie.' },
      },
      {
        kind: 'move',
        title: 'e4 schützen',
        prompt: { short: 'Jetzt droht …Sxe4 wirklich. Schütze e4 mit dem Turm.' },
        solution: ['Re1'],
        reply: 'b5',
        success: { short: '6.Te1 b5 – Schwarz vertreibt den Läufer, denn nach 7.Lxc6 dxc6 8.Sxe5 wäre e5 weg.' },
      },
      {
        kind: 'move',
        title: 'Die Diagonale halten',
        prompt: { short: 'Rette den Läufer – er soll weiter auf f7 zielen.' },
        solution: ['Bb3'],
        reply: 'd6',
        success: { short: '7.Lb3 d6 8.c3 – Weiß bereitet d4 vor und gibt dem Läufer mit c3 ein Rückzugsfeld c2.' },
      },
      {
        kind: 'info',
        title: 'Die Arche-Noah-Falle',
        fen: 'r1bqkbnr/2p2ppp/p1np4/1p2p3/B2PP3/5N2/PPP2PPP/RNBQK2R w KQkq b6 0 6',
        text: {
          short: 'Achtung Falle! Nach 1.e4 e5 2.Sf3 Sc6 3.Lb5 a6 4.La4 d6 5.d4 b5 6.Lb3 Sxd4 7.Sxd4 exd4 8.Dxd4?? c5! 9.Dd5 Le6 10.Dc6+ Ld7 11.Dd5 c4 ist der Läufer b3 gefangen.',
          why: 'Wie auf einer Arche sitzt der Läufer fest: a4, b5 und c4 bilden einen Käfig.',
          pro: 'Die Falle gibt es seit dem 19. Jahrhundert und sie fängt noch heute Großmeister in Blitzpartien. Merke: In der Spanischen mit …b5 immer an c5–c4 denken.',
        },
        arrows: ['c7c5', 'c5c4', 'b3'],
      },
    ],
    drill: [
      { name: 'Geschlossene Spanische', color: 'white', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O', 'h3'] },
      { name: 'Berliner Mauer', color: 'white', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Nxe4', 'd4', 'Nd6', 'Bxc6', 'dxc6', 'dxe5', 'Nf5', 'Qxd8+', 'Kxd8'] },
    ],
    takeaways: ['Lb5 greift den Verteidiger von e5 an.', 'e4 ist nach der Rochade durch Te1 geschützt.', 'c3 + d4 ist der Standardplan, h3 verhindert …Lg4.'],
    pitfalls: ['5.Sxe5?? in der Abtauschvariante (…Dd4!).', 'Die Arche-Noah-Falle mit …c5–c4.'],
  },
  {
    id: 'o-damengambit',
    title: 'Abgelehntes Damengambit',
    category: 'eroeffnungen',
    level: 2,
    summary: 'Klassisches 1.d4-Spiel: Druck auf d5, Fesselung mit Lg5 – und die Elefantenfalle.',
    steps: [
      {
        kind: 'move',
        title: 'Das Gambit',
        play: ['d4', 'd5'],
        prompt: {
          short: 'Biete einen Flügelbauern an, um das schwarze Zentrum anzugreifen.',
          why: 'Das „Gambit“ ist kein echtes Opfer: Nimmt Schwarz auf c4, holt Weiß den Bauern meist mit e3 und Lxc4 zurück und hat ein starkes Zentrum.',
        },
        solution: ['c4'],
        reply: 'e6',
        success: { short: '2.c4 e6 – Schwarz lehnt ab und stützt d5.' },
      },
      {
        kind: 'move',
        title: 'Druck auf d5',
        prompt: { short: 'Erhöhe den Druck auf d5.' },
        solution: ['Nc3'],
        reply: 'Nf6',
        success: { short: '3.Sc3 Sf6 – beide kämpfen um d5.' },
      },
      {
        kind: 'move',
        title: 'Die Fesselung',
        prompt: {
          short: 'Fessele den Springer, der d5 verteidigt.',
          why: 'Ein gefesselter Springer verteidigt schlechter – und Weiß kann später Lxf6 spielen.',
        },
        solution: ['Bg5'],
        reply: 'Nbd7',
        mistakes: [
          { soft: true, san: 'Bf4', text: { short: 'Auch gut (modernes 5.Lf4-System), aber die klassische Fesselung Lg5 übt mehr Druck auf d5 aus.' } },
        ],
        success: { short: '4.Lg5 Sbd7 – ein raffinierter Zug! Er stellt eine Falle.' },
      },
      {
        kind: 'move',
        title: 'Das Zentrum klären',
        prompt: { short: 'Tausche auf d5.', why: 'Der Abtausch klärt die Struktur und leitet oft die Karlsbader Struktur mit Minoritätsangriff ein.' },
        solution: ['cxd5'],
        reply: 'exd5',
        success: { short: '5.cxd5 exd5 – und jetzt? Der Bauer d5 scheint zu hängen …' },
      },
      {
        kind: 'move',
        title: 'Die Elefantenfalle',
        prompt: {
          short: 'Der Bauer d5 wird zweimal angegriffen und scheint nur einmal gedeckt. Schlägst du ihn?',
          why: 'Vorsicht! Der Springer f6 ist nur scheinbar gefesselt. Rechne: Sxd5 Sxd5! Lxd8 Lb4+ …',
        },
        solution: ['e3'],
        mistakes: [
          {
            san: 'Nxd5',
            text: {
              short: 'Die Elefantenfalle! Nach 6.Sxd5? Sxd5! 7.Lxd8 Lb4+ 8.Dd2 Lxd2+ 9.Kxd2 Kxd8 hat Schwarz eine Figur mehr.',
              why: 'Die Fesselung war nur relativ: Der Springer darf ziehen, weil Schwarz nach Lxd8 mit Schach zurückgewinnt.',
            },
          },
        ],
        success: {
          short: '6.e3 – solide! Weiß entwickelt weiter und spielt später Ld3, Dc2 und den Minoritätsangriff.',
          pro: 'Die Falle heißt „Elefantenfalle“, weil schon viele „starke“ Spieler hineingetappt sind. Merke: Relative Fesselungen sind keine Garantie.',
        },
      },
    ],
    drill: [
      { name: 'Klassisch mit Lg5', color: 'white', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'e3', 'O-O', 'Nf3', 'h6', 'Bh4', 'b6'] },
      { name: 'Abtauschvariante', color: 'white', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'cxd5', 'exd5', 'Bg5', 'c6', 'Qc2', 'Be7', 'e3', 'Nbd7', 'Bd3', 'O-O', 'Nf3'] },
    ],
    takeaways: ['2.c4 ist ein unechtes Gambit.', 'Lg5 fesselt den d5-Verteidiger.', 'Nicht in die Elefantenfalle tappen!'],
    pitfalls: ['6.Sxd5?? (Elefantenfalle).', 'Den Läufer f1 zu früh ziehen, bevor Schwarz auf c4 schlagen kann (Tempoverlust).'],
  },
  {
    id: 'o-franzoesisch',
    title: 'Französische Verteidigung',
    category: 'eroeffnungen',
    level: 2,
    orientation: 'black',
    summary: 'Solide Struktur, klarer Gegenangriff: …c5 und …f6 gegen die weiße Kette.',
    steps: [
      {
        kind: 'move',
        title: '1…e6',
        play: ['e4'],
        prompt: { short: 'Spiele die Französische Verteidigung.' },
        solution: ['e6'],
        reply: 'd4',
        success: { short: '1…e6 2.d4 – Schwarz bereitet …d5 vor.' },
      },
      {
        kind: 'move',
        title: 'Das Zentrum angreifen',
        prompt: { short: 'Greife e4 mit einem Bauern an.' },
        solution: ['d5'],
        reply: 'Nc3',
        success: { short: '2…d5 3.Sc3 – die Hauptvariante.' },
      },
      {
        kind: 'move',
        title: 'Klassisch',
        prompt: { short: 'Erhöhe den Druck auf e4 mit einer Figur.', why: 'Alternativ ist 3…Lb4 (Winawer) sehr scharf. Wir lernen die klassische Variante.' },
        solution: ['Nf6', 'Bb4'],
        reply: 'e5',
        success: { short: '3…Sf6 4.e5 – Weiß gewinnt Raum und vertreibt den Springer.' },
      },
      {
        kind: 'move',
        title: 'Der Rückzug',
        prompt: { short: 'Zieh den Springer zurück – auf ein Feld, von dem er später c5/f6 unterstützt.' },
        solution: ['Nfd7'],
        reply: 'f4',
        mistakes: [
          { san: 'Ne4', text: { short: 'Der Springer steht auf e4 unsicher: Nach Sxe4 dxe4 verliert Schwarz leicht den Bauern e4.' }, soft: true },
        ],
        success: { short: '4…Sfd7 5.f4 – Weiß baut das Zentrum massiv auf (Steinitz-Variante).' },
      },
      {
        kind: 'move',
        title: 'Die Basis angreifen',
        prompt: { short: 'Greife die weiße Bauernkette an ihrer Basis an!' },
        solution: ['c5'],
        reply: 'Nf3',
        success: {
          short: '5…c5! 6.Sf3 – der typische französische Gegenschlag.',
          why: 'Die Basis der Kette ist d4. Nach …cxd4 und …Sc6 steht Schwarz aktiv.',
        },
      },
      {
        kind: 'move',
        title: 'Druck aufbauen',
        prompt: { short: 'Entwickle den Damenspringer mit Druck auf d4.' },
        solution: ['Nc6'],
        reply: 'Be3',
        success: {
          short: '6…Sc6 7.Le3 – d4 wird dreimal angegriffen und dreimal verteidigt.',
          pro: 'Hauptlinie: 7…cxd4 8.Sxd4 Lc5 9.Dd2 O-O 10.O-O-O a6 – scharfe Stellungen mit entgegengesetzten Rochaden.',
        },
      },
    ],
    drill: [
      { name: 'Steinitz-Variante', color: 'black', moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'e5', 'Nfd7', 'f4', 'c5', 'Nf3', 'Nc6', 'Be3', 'cxd4', 'Nxd4', 'Bc5', 'Qd2', 'O-O'] },
      { name: 'Vorstoßvariante', color: 'black', moves: ['e4', 'e6', 'd4', 'd5', 'e5', 'c5', 'c3', 'Nc6', 'Nf3', 'Qb6', 'a3', 'c4'] },
    ],
    takeaways: ['…c5 greift die Basis an.', 'Später …f6 gegen die Spitze.', 'Der Läufer c8 ist das Sorgenkind.'],
    pitfalls: ['Passiv warten, statt mit …c5 und …f6 zu kontern.'],
  },
  {
    id: 'o-carokann',
    title: 'Caro-Kann-Verteidigung',
    category: 'eroeffnungen',
    level: 2,
    orientation: 'black',
    summary: 'Wie Französisch, aber mit freiem Läufer c8: solide, strukturell gesund.',
    steps: [
      {
        kind: 'move',
        title: '1…c6',
        play: ['e4'],
        prompt: { short: 'Spiele Caro-Kann: bereite …d5 mit dem c-Bauern vor.' },
        solution: ['c6'],
        reply: 'd4',
        success: { short: '1…c6 2.d4 – als Nächstes …d5.' },
      },
      {
        kind: 'move',
        title: 'Das Zentrum',
        prompt: { short: 'Greife e4 an.' },
        solution: ['d5'],
        reply: 'Nc3',
        success: { short: '2…d5 3.Sc3 – die klassische Hauptvariante.' },
      },
      {
        kind: 'move',
        title: 'Tauschen',
        prompt: { short: 'Tausche im Zentrum.' },
        solution: ['dxe4'],
        reply: 'Nxe4',
        success: { short: '3…dxe4 4.Sxe4 – jetzt der Schlüsselzug.' },
      },
      {
        kind: 'move',
        title: 'Der befreite Läufer',
        prompt: {
          short: 'Entwickle den Läufer c8 mit Tempo.',
          why: 'Das ist der große Vorteil gegenüber Französisch: Der Läufer kommt heraus, bevor …e6 ihn einsperrt.',
        },
        solution: ['Bf5'],
        reply: 'Ng3',
        mistakes: [
          { soft: true, san: 'e6', text: { short: 'Jetzt ist es Französisch mit weniger Möglichkeiten: Der Läufer c8 ist eingesperrt.' } },
        ],
        success: { short: '4…Lf5 5.Sg3 Lg6 – der Läufer zieht sich zurück und bleibt aktiv.' },
      },
      {
        kind: 'move',
        title: 'Rückzug',
        prompt: { short: 'Der Läufer wird angegriffen. Wohin?' },
        solution: ['Bg6'],
        reply: 'h4',
        success: { short: '5…Lg6 6.h4 – Weiß droht h5 und will den Läufer vertreiben.' },
      },
      {
        kind: 'move',
        title: 'Luft für den Läufer',
        prompt: { short: 'Weiß droht h5. Schaffe dem Läufer ein Rückzugsfeld.' },
        solution: ['h6'],
        reply: 'Nf3',
        mistakes: [
          { soft: true, san: 'Nf6', text: { short: 'Nach 7.h5 Lh7 ist das noch in Ordnung, aber Weiß gewinnt Raum. 6…h6 ist die Hauptvariante.' } },
        ],
        success: {
          short: '6…h6 7.Sf3 Sd7 8.h5 Lh7 – das bekannte Caro-Kann-Mittelspiel.',
          pro: 'Nach 9.Ld3 Lxd3 10.Dxd3 e6 ist Schwarz sehr solide. Karpow spielte das mit großem Erfolg.',
        },
      },
      {
        kind: 'move',
        title: 'Die Falle: Sd6 matt',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        play: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Nd7', 'Qe2', 'Ngf6'],
        prompt: {
          short: 'Nebenfalle: Nach 4…Sd7 5.De2 Sgf6?? kann Weiß sofort mattsetzen. Findest du den Zug?',
          why: 'Der Bauer e7 kann nicht mehr ziehen, der König ist eingemauert – und der Springer hat ein Schachfeld.',
        },
        solution: ['Nd6#'],
        success: {
          short: 'Sd6 matt! Die Dame e2 fesselt e7, der König hat keine Fluchtfelder.',
          why: 'Eine berühmte Falle aus Caro-Kann-Nebenvarianten. Deshalb: Nicht den Springer f6 ziehen, bevor e7 frei ist.',
        },
      },
    ],
    drill: [
      { name: 'Klassische Hauptvariante', color: 'black', moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6', 'h4', 'h6', 'Nf3', 'Nd7', 'h5', 'Bh7', 'Bd3', 'Bxd3', 'Qxd3', 'e6'] },
      { name: 'Vorstoßvariante', color: 'black', moves: ['e4', 'c6', 'd4', 'd5', 'e5', 'Bf5', 'Nf3', 'e6', 'Be2', 'c5', 'O-O', 'Nc6'] },
    ],
    takeaways: ['Läufer c8 raus VOR …e6.', 'Gegen h4: …h6.', 'Solide Struktur, wenig Schwächen.'],
    pitfalls: ['…e6 vor …Lf5 (eingesperrter Läufer).', 'Die Sd6#-Falle.'],
  },
  {
    id: 'o-sizilianisch',
    title: 'Sizilianisch Najdorf',
    category: 'eroeffnungen',
    level: 3,
    orientation: 'black',
    summary: 'Die Waffe von Fischer und Kasparow: unausgeglichen, dynamisch, auf Sieg gespielt.',
    steps: [
      {
        kind: 'move',
        title: '1…c5',
        play: ['e4'],
        prompt: {
          short: 'Kontrolliere d4 von der Seite.',
          why: 'Sizilianisch schafft ein Ungleichgewicht: Schwarz tauscht einen Flügelbauern (c) gegen einen Zentrumsbauern (d) und bekommt die halboffene c-Linie.',
        },
        solution: ['c5'],
        reply: 'Nf3',
        success: { short: '1…c5 2.Sf3 – die Offene Sizilianische wird vorbereitet.' },
      },
      {
        kind: 'move',
        title: 'd6',
        prompt: { short: 'Kontrolliere e5 und öffne den Läufer c8.' },
        solution: ['d6'],
        reply: 'd4',
        success: { short: '2…d6 3.d4 – Weiß öffnet das Zentrum.' },
      },
      {
        kind: 'move',
        title: 'Der Tausch',
        prompt: { short: 'Tausche auf d4.', why: 'Das ist der Kern von Sizilianisch: c-Bauer gegen d-Bauer.' },
        solution: ['cxd4'],
        reply: 'Nxd4',
        success: { short: '3…cxd4 4.Sxd4 – Schwarz hat zwei Zentrumsbauern (d, e), Weiß nur einen.' },
      },
      {
        kind: 'move',
        title: 'Angriff auf e4',
        prompt: { short: 'Entwickle mit Angriff auf e4.' },
        solution: ['Nf6'],
        reply: 'Nc3',
        success: { short: '4…Sf6 5.Sc3 – jetzt kommt der berühmte Zug.' },
      },
      {
        kind: 'move',
        title: 'Najdorf!',
        prompt: {
          short: 'Der Najdorf-Zug: ein kleiner Bauernzug mit großer Wirkung.',
          why: 'Er kontrolliert b5 (keine Sb5 oder Lb5+ mehr), bereitet …e5 und …b5 vor und hält alle Optionen offen.',
        },
        solution: ['a6'],
        reply: 'Be3',
        mistakes: [
          { soft: true, san: 'g6', text: { short: 'Das ist der Drache – eine andere, ebenso berühmte Variante. Heute lernen wir Najdorf mit 5…a6.' } },
        ],
        success: {
          short: '5…a6 6.Le3 – der Englische Angriff. Weiß plant f3, Dd2, O-O-O und g4.',
          pro: 'Andere Hauptzüge: 6.Lg5 (Hauptvariante, „Vergifteter Bauer“ nach 6…e6 7.f4 Db6), 6.Le2 (klassisch), 6.h3 und 6.Lc4 (Fischer-Sozin).',
        },
      },
      {
        kind: 'move',
        title: 'Raum im Zentrum',
        prompt: { short: 'Vertreibe den Springer d4 und beanspruche Raum.' },
        solution: ['e5', 'e6'],
        reply: 'Nb3',
        success: {
          short: '6…e5 7.Sb3 – Schwarz akzeptiert das Loch auf d5 für Raum und Tempo.',
          pro: 'Der Kampf um d5 (siehe Lektion „Vorposten“) prägt die ganze Partie. …Le6 und …Sbd7–b6 kontrollieren d5.',
        },
      },
      {
        kind: 'move',
        title: 'Um d5 kämpfen',
        prompt: { short: 'Entwickle den Läufer c8 so, dass er d5 kontrolliert.' },
        solution: ['Be6'],
        reply: 'f3',
        success: {
          short: '7…Le6 8.f3 Le7 9.Dd2 O-O 10.O-O-O Sbd7 11.g4 b5 – Angriff gegen Angriff!',
          why: 'Entgegengesetzte Rochaden bedeuten: Wer schneller angreift, gewinnt. Schwarz stürmt mit …b5–b4, Weiß mit g4–g5.',
        },
      },
    ],
    drill: [
      { name: 'Englischer Angriff', color: 'black', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e5', 'Nb3', 'Be6', 'f3', 'Be7', 'Qd2', 'O-O', 'O-O-O', 'Nbd7', 'g4', 'b5'] },
      { name: 'Klassisch 6.Le2', color: 'black', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be2', 'e5', 'Nb3', 'Be7', 'O-O', 'O-O', 'Be3', 'Be6'] },
    ],
    takeaways: ['c-Bauer gegen d-Bauer: dynamisches Ungleichgewicht.', '…a6 kontrolliert b5 und hält Optionen offen.', 'Das Loch auf d5 ist der strategische Kern.'],
    pitfalls: ['Zu langsam angreifen bei entgegengesetzten Rochaden.', 'd5 kampflos aufgeben.'],
  },
  {
    id: 'o-koenigsindisch',
    title: 'Königsindische Verteidigung',
    category: 'eroeffnungen',
    level: 3,
    orientation: 'black',
    summary: 'Erst Weiß das Zentrum überlassen, dann mit …e5 und …f5 zum Königsangriff.',
    steps: [
      {
        kind: 'info',
        play: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2'],
        text: {
          short: 'Schwarz fianchettiert den Läufer, rochiert schnell und lässt Weiß das große Zentrum (c4, d4, e4).',
          why: 'Die hypermoderne Idee: Das Zentrum wird nicht besetzt, sondern später angegriffen – mit …e5 oder …c5.',
          pro: 'Kasparow, Fischer und Bronstein machten Königsindisch berühmt. Es ist eine Eröffnung für Spieler, die auf Sieg spielen wollen.',
        },
        arrows: ['g7d4', 'c4', 'd4', 'e4'],
      },
      {
        kind: 'move',
        title: 'Der Zentrumsschlag',
        prompt: { short: 'Greife das weiße Zentrum an!' },
        solution: ['e5'],
        reply: 'O-O',
        mistakes: [
          { soft: true, san: 'c5', text: { short: 'Auch ein Zentrumsschlag (Benoni-Charakter), aber die klassische Königsindisch-Idee ist …e5.' } },
        ],
        success: {
          short: '6…e5 7.O-O – Achtung: 7.dxe5 dxe5 8.Dxd8 Txd8 9.Sxe5?? verliert nach 9…Sxe4! Material.',
          why: 'Nach 9…Sxe4 10.Sxe4 Lxe5 hat Schwarz den Bauern zurück und die bessere Stellung.',
        },
      },
      {
        kind: 'move',
        title: 'Spannung erhöhen',
        prompt: { short: 'Entwickle den Damenspringer mit Druck auf d4.' },
        solution: ['Nc6'],
        reply: 'd5',
        success: { short: '7…Sc6 8.d5 – Weiß schließt das Zentrum. Jetzt entscheiden die Flügel.' },
      },
      {
        kind: 'move',
        title: 'Richtung Königsflügel',
        prompt: {
          short: 'Der Springer wird angegriffen. Wohin – im Hinblick auf den Königsflügelangriff?',
          why: 'Im geschlossenen Zentrum greift Schwarz am Königsflügel an (…f5). Der Springer soll dort helfen.',
        },
        solution: ['Ne7'],
        reply: 'Ne1',
        mistakes: [
          { soft: true, san: 'Nb8', text: { short: 'Passiv. Von e7 aus unterstützt der Springer …f5 und kann nach g6 oder f5.' } },
        ],
        success: { short: '8…Se7 9.Se1 – Weiß plant f3 und c5 am Damenflügel.' },
      },
      {
        kind: 'move',
        title: 'f5 vorbereiten',
        prompt: { short: 'Mach den f-Bauern frei.', why: 'Der Springer f6 steht vor dem f-Bauern. Wo kann er hin, um …f5 zu unterstützen?' },
        solution: ['Nd7', 'Ne8'],
        reply: 'Be3',
        success: { short: '9…Sd7 10.Le3 – jetzt der typische Hebel.' },
      },
      {
        kind: 'move',
        title: 'Der Hebel',
        prompt: { short: 'Greife mit dem f-Bauern an!' },
        solution: ['f5'],
        success: {
          short: '10…f5! Das Mar-del-Plata-System: Schwarz stürmt am Königsflügel (…f4, …g5, …g4), Weiß am Damenflügel (f3, c5).',
          pro: 'Wer schneller ist, gewinnt. Schwarz opfert am Ende oft auf h3 oder g2 – Weiß bricht auf c7 ein. Hochspannung pur.',
        },
        successArrows: ['f5f4', 'g7g5', 'g5g4'],
      },
    ],
    drill: [
      { name: 'Mar del Plata', color: 'black', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6', 'd5', 'Ne7', 'Ne1', 'Nd7', 'Be3', 'f5'] },
    ],
    takeaways: ['Fianchetto, Rochade, dann …e5.', 'Geschlossenes Zentrum → Königsflügelangriff mit …f5.', 'Rennen: Wer ist schneller?'],
    pitfalls: ['Nach dxe5 dxe5 Dxd8 Txd8 an Sxe4-Tricks denken.', 'Zu langsam angreifen, während Weiß auf c7 einbricht.'],
  },
];
