import type { Lesson } from '../types';

// Aufgaben aus der Lichess-Puzzle-Datenbank (CC0), erklärt und mit Stockfish geprüft.
export const taktik2: Lesson[] = [
  {
    id: 't-zwischenzug',
    title: 'Der Zwischenzug',
    category: 'taktik',
    level: 3,
    summary: 'Nicht sofort zurückschlagen – erst einen stärkeren Zug einschieben.',
    steps: [
      {
        kind: 'info',
        title: 'Die gefährlichste Annahme',
        fen: 'r2q2k1/5ppp/8/8/8/2b5/PP3PPP/3Q2K1 w - - 0 1',
        text: {
          short: '„Er muss ja zurückschlagen“ – diese Annahme kostet unzählige Partien. Ein Zwischenzug ist ein forcierender Zug (meist Schach oder Schlagen), der VOR dem erwarteten Zurückschlagen kommt.',
          why: 'Hier hat Schwarz gerade auf c3 geschlagen. Statt sofort bxc3 kann Weiß zuerst Dxd8+ spielen – Schwarz muss reagieren, danach wird trotzdem zurückgeschlagen.',
          pro: 'Kasparows Faustregel: Prüfe bei jedem Abtausch, ob es für BEIDE Seiten einen Zwischenzug gibt. Oft entscheidet der Zwischenzug des Gegners, den man übersehen hat.',
        },
        arrows: ['d1d8', '?b2c3'],
      },
      {
        kind: 'move',
        title: 'Aufgabe 1',
        fen: '5Q2/6rp/5p1k/6r1/P2p4/3P1q1P/1PP3P1/6RK w - - 0 43',
        prompt: {
          short: 'Die schwarze Dame hat gerade auf f3 geschlagen. Schlägst du sofort zurück?',
          why: 'Schau dir die g-Linie an: Was passiert mit den schwarzen Türmen, wenn der g-Bauer wegzieht?',
        },
        solution: ['Qxg7+'],
        reply: 'Rxg7',
        mistakes: [
          {
            san: 'gxf3',
            text: {
              short: 'Nach gxf3 ist die g-Linie offen: …Txg1+ mit Angriff der beiden Türme gegen deinen König.',
              why: 'Das naheliegende Zurückschlagen öffnet genau die Linie, die der Gegner braucht.',
            },
          },
        ],
        success: {
          short: 'Dxg7+! Der Damentausch mit Schach kommt zuerst – danach ist die g-Linie für Schwarz entschärft.',
        },
      },
      {
        kind: 'move',
        title: 'Jetzt zurückschlagen',
        prompt: { short: 'Und nun die schwarze Dame.' },
        solution: ['gxf3'],
        success: { short: 'gxf3 – Weiß steht mit Turm gegen Turm und besserer Struktur klar auf Gewinn.' },
      },
      {
        kind: 'move',
        title: 'Aufgabe 2',
        fen: 'r3k2r/p1q1Bppp/2p1p3/8/8/8/PPP1QnPP/R2R2K1 w kq - 0 15',
        prompt: {
          short: 'Der Springer f2 gabelt deine Türme. Sofort Dxf2? Prüfe erst, was die schwarze Dame dann hat!',
          why: 'Die Dame c7 blickt über die Diagonale c7–h2 auf deinen Bauern h2 – mit Schach.',
        },
        solution: ['Bd6'],
        reply: 'Qb6',
        mistakes: [
          {
            san: 'Qxf2',
            text: { short: 'Dxf2?? Dxh2+ – die Dame schlüpft mit Schach herein und Weiß steht schlecht.' },
          },
        ],
        success: {
          short: 'Ld6! greift die Dame an UND sperrt die Diagonale c7–h2. Erst danach wird der Springer geschlagen.',
          pro: 'Ein Zwischenzug mit doppelter Funktion: Tempo gewinnen und eine gegnerische Ressource ausschalten.',
        },
      },
      {
        kind: 'move',
        title: 'Die Ernte',
        prompt: { short: 'Jetzt schlag den Springer.' },
        solution: ['Qxf2'],
        reply: 'Qxf2+',
        success: { short: 'Dxf2 Dxf2+ – und nun zurückschlagen.' },
      },
      {
        kind: 'move',
        title: 'Abschluss',
        prompt: { short: 'Schlag zurück.' },
        solution: ['Kxf2'],
        success: { short: 'Kxf2 – eine Figur mehr für Weiß.' },
      },
      {
        kind: 'move',
        title: 'Aufgabe 3',
        fen: '6k1/p2n2p1/1p2qb1p/3br3/1P1Q4/P5PP/1BP4K/3RR3 w - - 0 28',
        prompt: {
          short: 'Schwarz hat auf d5 geschlagen. Dxd5 liegt nahe – aber was steht dann auf e1?',
          why: 'Nach Dxd5 Dxd5 Txd5 hängt dein Turm e1 – der schwarze Turm e5 schlägt ihn.',
        },
        solution: ['Rxe5'],
        reply: 'Nxe5',
        mistakes: [
          { san: 'Qxd5', text: { short: 'Dxd5 Dxd5 Txd5 Txe1 – du verlierst den Turm e1.' } },
        ],
        success: { short: 'Txe5! beseitigt zuerst den gefährlichen Turm. Jetzt kann Weiß in Ruhe auf d5 schlagen.' },
      },
      {
        kind: 'move',
        title: 'Weiter',
        prompt: { short: 'Nun der Läufer d5.' },
        solution: ['Qxd5'],
        reply: 'Qxd5',
        success: { short: 'Dxd5 Dxd5 – schlag zurück.' },
      },
      {
        kind: 'move',
        title: 'Abschluss',
        prompt: { short: 'Zurückschlagen.' },
        solution: ['Rxd5'],
        success: { short: 'Txd5 – Weiß hat eine Figur gewonnen.' },
      },
    ],
    takeaways: ['Vor jedem Zurückschlagen: Gibt es einen forcierenden Zwischenzug?', 'Zwischenzüge mit Schach oder Angriff auf die Dame sind die häufigsten.'],
    pitfalls: ['Automatisch zurückschlagen.', 'Den Zwischenzug des Gegners übersehen.'],
  },
  {
    id: 't-roentgen',
    title: 'Röntgenangriff und Grundreihe',
    category: 'taktik',
    level: 3,
    summary: 'Schwerfiguren wirken durch andere hindurch – besonders auf der Grundreihe.',
    steps: [
      {
        kind: 'info',
        fen: '3r2k1/5ppp/8/8/8/8/3R1PPP/3R2K1 w - - 0 1',
        text: {
          short: 'Zwei Türme hintereinander auf einer Linie: Der hintere „sieht“ durch den vorderen hindurch. Das nennt man Röntgenangriff (X-Ray).',
          why: 'Nach einem Abtausch auf der Linie übernimmt der hintere Turm sofort. Beim Zählen von Angreifern und Verteidigern zählt er also mit.',
          pro: 'Röntgenangriffe entscheiden besonders oft Grundreihen-Situationen: Ein Verteidiger scheint zu reichen, aber die zweite Figur dahinter gibt den Ausschlag.',
        },
        arrows: ['d1d8'],
      },
      {
        kind: 'move',
        title: 'Aufgabe 1',
        fen: '5r1k/p4r1p/q7/3R3Q/1P4p1/P7/5RPP/1B5K b - - 0 31',
        prompt: {
          short: 'Schwarz am Zug: Setze in zwei Zügen matt!',
          why: 'Die schwarzen Türme f7 und f8 stehen hintereinander auf der f-Linie. Welche Figur kann sich für sie opfern?',
        },
        solution: ['Qf1+'],
        reply: 'Rxf1',
        success: { short: '…Df1+!! Txf1 – die Dame lenkt den Turm ab, jetzt schlägt der schwarze Turm mit Röntgen-Unterstützung.' },
      },
      {
        kind: 'move',
        title: 'Matt',
        prompt: { short: 'Vollende das Matt.' },
        solution: ['Rxf1#'],
        success: { short: '…Txf1# – der Turm f7 hält die f-Linie, der weiße König hat keine Flucht.' },
      },
      {
        kind: 'move',
        title: 'Aufgabe 2',
        fen: '3Rn2k/p1p3pp/2p1r3/2q5/P1P5/8/5PPP/4R1K1 w - - 0 25',
        prompt: {
          short: 'Weiß am Zug: Nutze die Grundreihe und setze matt.',
          why: 'Der Springer e8 wird zweimal angegriffen (Td8 und – durch den Turm e6 hindurch – Te1).',
        },
        solution: ['Rxe8+'],
        reply: 'Rxe8',
        success: { short: 'Txe8+! Txe8 – jetzt ist die e-Linie offen.' },
      },
      {
        kind: 'move',
        title: 'Weiter',
        prompt: { short: 'Mit Schach weiter!' },
        solution: ['Rxe8+'],
        reply: 'Qf8',
        success: { short: 'Txe8+ Df8 – die Dame muss dazwischen.' },
      },
      {
        kind: 'move',
        title: 'Matt',
        prompt: { short: 'Setze matt.' },
        solution: ['Rxf8#'],
        success: { short: 'Txf8# – klassisches Grundreihenmatt.' },
      },
    ],
    takeaways: ['Hintereinanderstehende Schwerfiguren zählen beim Abtausch doppelt.', 'Grundreihenschwäche + Röntgen = oft Matt.'],
  },
  {
    id: 't-raeumung',
    title: 'Räumung und Verstellung',
    category: 'taktik',
    level: 3,
    summary: 'Ein Opfer macht den Weg frei – oder verstopft den Weg des Verteidigers.',
    steps: [
      {
        kind: 'info',
        fen: 'r1bq1rk1/p3bpp1/1p2p2p/8/4Nn2/P2Q1N2/1P3RPP/1BR3K1 w - - 1 17',
        text: {
          short: 'Die Batterie Dd3 + Lb1 zielt auf h7 – aber der eigene Springer e4 steht im Weg. Eine **Räumung** macht die Linie frei, am besten mit Tempo.',
          why: 'Zieht die blockierende Figur mit Schach weg, hat der Gegner keine Zeit, die frei gewordene Linie zu verteidigen.',
          pro: 'Verwandte Idee: die **Verstellung** – man stellt eine Figur zwischen zwei gegnerische, die sich gegenseitig decken.',
        },
        arrows: ['b1h7', 'e4'],
      },
      {
        kind: 'move',
        title: 'Aufgabe 1',
        prompt: { short: 'Räume die Diagonale – mit Schach!' },
        solution: ['Nf6+'],
        reply: 'gxf6',
        success: { short: 'Sf6+! gxf6 – die Diagonale b1–h7 ist frei.' },
      },
      {
        kind: 'move',
        title: 'Matt',
        prompt: { short: 'Setze matt.' },
        solution: ['Qh7#'],
        success: { short: 'Dh7# – gedeckt vom Läufer b1.' },
      },
      {
        kind: 'move',
        title: 'Aufgabe 2',
        fen: 'r2q1r2/1bp1n2k/p2pB1pp/1pn5/3B4/2PQ1N2/P1P2PPP/R3R1K1 w - - 3 18',
        prompt: {
          short: 'Die Dame will nach h3 – aber das Feld wird kontrolliert? Finde das Matt in zwei.',
          why: 'Ein Springeropfer mit Schach öffnet die h-Linie für die Dame.',
        },
        solution: ['Ng5+'],
        reply: 'hxg5',
        success: { short: 'Sg5+! hxg5 – der h-Bauer ist weg, die h-Linie offen.' },
      },
      {
        kind: 'move',
        title: 'Matt',
        prompt: { short: 'Und jetzt?' },
        solution: ['Qh3#'],
        success: { short: 'Dh3# – der Läufer e6 nimmt dem König g8, die Dame deckt die h-Linie.' },
      },
      {
        kind: 'move',
        title: 'Aufgabe 3 (Schwarz)',
        fen: '4rr1k/2Q3pn/p6p/3p4/N7/1P4R1/P1P1qPPP/5RK1 b - - 0 27',
        prompt: {
          short: 'Schwarz am Zug: Matt in drei!',
          why: 'Der Turm f8 wird von f2 abgeschirmt. Welches Opfer räumt den Weg auf die Grundreihe?',
        },
        solution: ['Qxf2+'],
        reply: 'Rxf2',
        success: { short: '…Dxf2+!! Txf2 – der Turm f1 wurde weggelockt, die Grundreihe ist schwach.' },
      },
      {
        kind: 'move',
        title: 'Weiter',
        prompt: { short: 'Schach auf der Grundreihe!' },
        solution: ['Re1+'],
        reply: 'Rf1',
        success: { short: '…Te1+ Tf1 – der Turm muss zurück.' },
      },
      {
        kind: 'move',
        title: 'Matt',
        prompt: { short: 'Vollende.' },
        solution: ['Rexf1#'],
        success: { short: '…Texf1# – der zweite Turm auf f8 gab die entscheidende Röntgen-Unterstützung.' },
      },
    ],
    takeaways: ['Räumung: eigene Figur mit Tempo aus dem Weg ziehen.', 'Oft ist die blockierende Figur die, die geopfert wird.'],
  },
  {
    id: 't-stiller-zug',
    title: 'Der stille Zug',
    category: 'taktik',
    level: 4,
    summary: 'Kein Schach, kein Schlagen – und trotzdem nicht zu verteidigen.',
    steps: [
      {
        kind: 'info',
        fen: '1r3rk1/1p3pp1/1q6/p2p2PQ/8/P7/1bP1R3/4R2K w - - 0 28',
        text: {
          short: 'Wir suchen zuerst Schachs, Schläge und Drohungen. Die stärksten Züge sind manchmal aber leise: ein Zug, der eine unaufhaltsame Drohung aufstellt.',
          why: 'Stille Züge sind schwer zu finden, weil das Gehirn forcierende Züge bevorzugt. Frage: „Welche Figur fehlt noch im Angriff?“',
          pro: 'Klassiker: der stille Turmhebel auf die h-Linie oder ein Königszug, der eine Deckung aufhebt.',
        },
        arrows: ['h5h8'],
      },
      {
        kind: 'move',
        title: 'Aufgabe 1',
        prompt: {
          short: 'Die Dame h5 und der Bauer g5 stehen bereit. Welche Figur fehlt noch für den Angriff auf der h-Linie?',
        },
        solution: ['Rh2'],
        reply: 'Qh6',
        success: {
          short: 'Th2! – still, aber tödlich: Es droht Dh8#. Schwarz kann nur mit …Dh6 die Dame geben.',
          why: 'Die Batterie Th2 + Dh5 lässt sich auf der h-Linie nicht mehr aufhalten.',
        },
      },
      {
        kind: 'move',
        title: 'Die Dame gewinnen',
        prompt: { short: 'Schlag die Dame.' },
        solution: ['gxh6'],
        success: { short: 'gxh6 – Weiß hat eine Dame mehr.' },
      },
      {
        kind: 'move',
        title: 'Aufgabe 2',
        fen: 'r4rk1/p2pppbp/b1p2np1/8/8/P1B2Q2/2P2PPP/RNqBK2R w KQ - 1 14',
        prompt: {
          short: 'Die schwarze Dame c1 ist tief eingedrungen. Mit einem leisen Zug sperrst du ihr alle Wege ab.',
          why: 'Welche Felder hat die Dame noch? Ein Springerzug nimmt ihr die letzten Ausgänge.',
        },
        solution: ['Nd2'],
        reply: 'Qxa1',
        success: { short: 'Sd2! – die Dame ist gefangen. Sie nimmt noch den Turm a1, aber dann schlägt der Läufer.' },
      },
      {
        kind: 'move',
        title: 'Die Falle schließt sich',
        prompt: { short: 'Schlag die Dame.' },
        solution: ['Bxa1'],
        success: { short: 'Lxa1 – Dame gegen Turm gewonnen.' },
      },
    ],
    takeaways: ['Wenn forcierende Züge nichts bringen: nach stillen Zügen suchen.', 'Frage: Welche Figur fehlt noch? Welche Deckung muss weg?'],
  },
  {
    id: 't-mattbilder-2',
    title: 'Mattbilder II: Anastasia, Boden, Epaulette',
    category: 'taktik',
    level: 2,
    summary: 'Drei weitere Mattbilder, die in Partien immer wieder auftauchen.',
    steps: [
      {
        kind: 'move',
        title: 'Anastasias Matt',
        fen: '8/4N1pk/8/8/8/K7/8/R7 w - - 0 1',
        prompt: {
          short: 'Der Springer e7 kontrolliert g8 und g6. Setze mit dem Turm matt!',
          why: 'Das Muster: König am Rand, eigener g-Bauer daneben, Springer e7 und Turm auf der h-Linie.',
        },
        solution: ['Rh1#'],
        success: { short: 'Th1# – Anastasias Matt: g8 und g6 deckt der Springer, g7 ist vom eigenen Bauern besetzt.' },
      },
      {
        kind: 'move',
        title: 'Bodens Matt',
        fen: '2kr4/3n4/8/8/5B2/8/4B3/6K1 w - - 0 1',
        prompt: {
          short: 'Zwei Läufer auf sich kreuzenden Diagonalen – setze matt!',
          why: 'Der Läufer f4 kontrolliert b8 und c7. Welches Feld braucht der andere Läufer?',
        },
        solution: ['Ba6#'],
        success: { short: 'La6# – Bodens Matt. Der König ist von eigenen Figuren eingemauert, die Läufer schließen die Diagonalen.' },
      },
      {
        kind: 'move',
        title: 'Epaulettenmatt',
        fen: '3rkr2/8/8/8/2Q5/8/8/6K1 w - - 0 1',
        prompt: {
          short: 'Der König steht zwischen seinen Türmen wie zwischen zwei Schulterklappen. Setze matt!',
        },
        solution: ['Qe6#'],
        mistakes: [{ san: 'Qc6+', text: { short: 'Schach, aber …Td7 blockt. Die Dame muss direkt vor den König – auf Abstand, damit er sie nicht schlagen kann.' } }],
        success: { short: 'De6# – d7 und f7 sind kontrolliert, d8 und f8 von den eigenen Türmen besetzt.' },
      },
    ],
    takeaways: ['Anastasia: Springer e7 + Turm auf der h-Linie.', 'Boden: zwei Läufer über Kreuz.', 'Epaulette: König zwischen eigenen Figuren.'],
  },
];
